var repeat = false;
var appeared = [];
const list_word = [
  ["pen", "bút mực", "/pen/"],
  ["pencil", "bút chì", "/ˈpensl/"],
  ["paper", "giấy", "/ˈpeɪpər/"],
  ["eraser", "cục tẩy, cục gôm", "/ɪˈreɪsər/"],
  ["pencil sharpener", "đồ chuốt, đồ gọt bút chì", "/ˈpensl ʃɑːrpnər/"],
  ["book", "quyển sách, tác phẩm", "/bʊk/"],
  ["pack", "túi đeo, ba lô", "/pæk/"],
  ["crayon", "bút màu sáp", "/ˈkreɪən/"],
  ["scissors", "cái kéo", "/ˈsɪzərz/"],
  ["glue", "keo, hồ dán", "/ɡluː/"],
  ["calculator", "máy tính (toán)", "/ˈkælkjuleɪtər/"],
  ["compass", "com-pa", "/ˈkʌmpəs/"],
  ["bag", "túi, giỏ", "/bæɡ/"],
  ["ruler", "cây thước", "/ˈruːlər/"],
  ["board", "tấm bảng", "/bɔːrd/"],
  ["chalk", "phấn, viên phấn", "/tʃɔːk/"],
  ["dictionary", "từ điển", "/ˈdɪkʃəneri/"],
  ["watercolour", "màu nước", "/ˈwɔːtərkʌlər/"],
  ["globe", "quả địa cầu", "/ɡləʊb/"],
  ["protractor", "thước đo độ", "/prəˈtræktər/"],
  ["stapler", "đồ bấm kim", "/ˈsteɪplər/"],
  ["paintbrush", "cọ quét (sơn)", "/ˈpeɪntbrʌʃ/"],
  ["paper clip", "kẹp giấy", "/ˈpeɪpər klɪp/"],
  ["march", "cuộc diễu hành", "/mɑːrtʃ/"],
  ["walk", "bước đi, đi bộ", "/wɔːk/"],
  ["crawl", "bò, trườn", "/krɔːl/"],
  ["drag", "kéo, níu kéo", "/dræɡ/"],
  ["push", "đẩy, xô", "/pʊʃ/"],
  ["jump", "nhảy, nhảy lên", "/dʒʌmp/"],
  ["leap", "nhảy dài; nhảy vọt", "/liːp/"],
  ["skipping", "(trò) nhảy dây", "None"],
  ["hit", "đập, va phải", "/hɪt/"],
  ["stretch", "duỗi, căng (cơ thể)", "/stretʃ/"],
  ["lift", "nhấc, nâng lên", "/lɪft/"],
  ["put down", "đặt xuống, để xuống", "None"],
  ["dive", "nhảy lao đầu xuống (nước)", "/daɪv/"],
  ["lean", "ngả, nghiêng về", "/liːn/"],
  ["sit", "ngồi", "/sɪt/"],
  ["bend", "uốn lượn, bẻ cong", "/bend/"],
  ["hold", "cầm, nắm, giữ, ôm lấy", "/həʊld/"],
  ["carry", "mang, đưa đi, chở đi", "/ˈkæri/"],
  ["slap", "tát, vỗ", "/slæp/"],
  ["punch", "đấm", "/pʌntʃ/"],
  ["kick", "đá, sút", "/kɪk/"],
  ["catch", "bắt lấy, chụp lấy", "/kætʃ/"],
  ["throw", "ném, thảy, quăng", "/θrəʊ/"],
  ["pull", "kéo", "/pʊl/"],
  ["climb", "leo, trèo", "/klaɪm/"],
  ["fall", "rớt, rơi, ngã", "/fɔːl/"],
  ["point", "chỉ, trỏ", "/pɔɪnt/"],
  ["rake up", "cào, gom", "None"],
  ["read", "đọc", "/riːd/"],
  ["scrub", "chà, cọ rửa", "/skrʌb/"],
  ["set", "để, đặt", "/set/"],
  ["sew", "may, khâu", "/səʊ/"],
  ["pat", "vuốt nhẹ, vỗ nhẹ, thoa", "/pæt/"],
  ["shout", "la lối, hét lên", "/ʃaʊt/"],
  ["tickle", "thọc lét, cù lét", "/ˈtɪkl/"],
  ["tell", "nói, kể", "/tel/"],
  ["stand", "đứng", "/stænd/"],
  ["sneeze", "hắt hơi, nhảy mũi", "/sniːz/"],
  ["slip", "trượt (chân)", "/slɪp/"],
  ["sleep", "ngủ", "/sliːp/"],
  ["sing", "hát, ca hát", "/sɪŋ/"],
  ["brush your teeth", "Đánh rằng", "None"],
  ["buy", "mua", "/baɪ/"],
  ["comb", "chải (tóc)", "/kəʊm/"],
  ["cook", "đầu bếp, người nấu ăn", "/kʊk/"],
  ["homework", "bài tập về nhà", "/ˈhəʊmwɜːrk/"],
  ["eat in", "ăn ở nhà", "None"],
  ["eat out", "ra ngoài ăn, ăn ngoài", "None"],
  ["feed on", "cho ăn", "None"],
  ["get up", "thức dậy; đánh thức", "None"],
  ["go home", "về nhà", "None"],
  ["go to bed", "đi ngủ", "None"],
  ["garden", "làm vườn", "/ˈɡɑːrdn/"],
  ["go shopping", "đi mua sắm", "None"],
  ["have a break", "giải lao, nghỉ xả hơi", "None"],
  ["have breakfast", "ăn sáng, dùng bữa sáng", "None"],
  ["have lunch", "ăn trưa, dùng cơm trưa", "None"],
  ["have dinner", "ăn tối", "None"],
  ["take a shower", "đi tắm (vòi sen)", "None"],
  ["listen to music", "nghe nhạc", "None"],
  ["hang out", "đi chơi, tụ tập", "None"],
  ["read", "đọc", "/riːd/"],
  ["relax", "thư giãn, nghỉ xả hơi", "/rɪˈlæks/"],
  ["sleep", "ngủ", "/sliːp/"],
  ["study", "học", "/ˈstʌdi/"],
  ["surf the web", "lướt web", "None"],
  ["drink", "uống", "/drɪŋk/"],
  ["wake up", "thức giấc, tỉnh dậy; đánh thức", "None"],
  ["wash out", "giặt giũ, giặt sạch", "None"],
  ["wash", "rửa, giặt", "/wɑːʃ/"],
  ["watch", "xem, nhìn", "/wɑːtʃ/"],
  ["shave", "cạo râu", "/ʃeɪv/"],
  ["clean", "lau dọn, chùi rửa", "/kliːn/"],
  ["yawn", "ngáp", "/jɔːn/"],
  ["dust", "lau bụi", "/dʌst/"],
  ["sea", "biển", "/siː/"],
  ["ocean", "đại dương", "/ˈəʊʃn/"],
  ["wave", "con sóng", "/weɪv/"],
  ["island", "hòn đảo", "/ˈaɪlənd/"],
  ["submarine", "tàu ngầm", "/ˌsʌbməˈriːn/"],
  ["ship", "con tàu, con thuyền", "/ʃɪp/"],
  ["boat", "thuyền, tàu", "/bəʊt/"],
  ["captain", "thuyền trưởng, hạm trưởng", "/ˈkæptɪn/"],
  ["fisherman", "ngư dân", "/ˈfɪʃərmən/"],
  ["lifeguard", "nhân viên cứu hộ", "/ˈlaɪfɡɑːrd/"],
  ["seashore", "bờ biển", "/ˈsiːʃɔːr/"],
  ["beach", "bãi biển", "/biːtʃ/"],
  ["coast", "bờ biển", "/kəʊst/"],
  ["whale", "(loài) cá voi", "/weɪl/"],
  ["shark", "(loài) cá mập", "/ʃɑːrk/"],
  ["dolphin", "(loài) cá heo", "/ˈdɑːlfɪn/"],
  ["octopus", "(loài) bạch tuộc", "/ˈɑːktəpʊs/"],
  ["fish", "(thức ăn) cá", "/fɪʃ/"],
  ["jellyfish", "(loài) sứa", "/ˈdʒelifɪʃ/"],
  ["seaweed", "rong biển", "/ˈsiːwiːd/"],
  ["coral", "san hô", "/ˈkɔːrəl/"],
  ["coral reef", "rạn san hô", "None"],
  ["clam", "(loài) nghêu, ngao", "/klæm/"],
  ["starfish", "con sao biển", "/ˈstɑːrfɪʃ/"],
  ["turtle", "(loài) rùa biển", "/ˈtɜːrtl/"],
  ["crab", "(loài) cua", "/kræb/"],
  ["cardinal number", "số đếm", "None"],
  ["ordinal number", "số thứ tự", "None"],
  ["decimal", "(thuộc) thập phân", "/ˈdesɪml/"],
  ["fraction", "(toán học) phân số", "/ˈfrækʃn/"],
  ["percentage", "(tỷ lệ) phần trăm", "/pərˈsentɪdʒ/"],
  ["arithmetic", "(toán) số học", "/əˈrɪθmətɪk/"],
  ["divide", "(phép toán) chia", "/dɪˈvaɪd/"],
  ["plus", "(phép toán) cộng", "None"],
  ["minus", "(phép toán) trừ", "/ˈmaɪnəs/"],
  ["multiply", "(toán) nhân, tính tích", "/ˈmʌltɪplaɪ/"],
  ["equal", "ngang bằng, như nhau", "/ˈiːkwəl/"],
  ["total", "tổng, tổng số", "/ˈtəʊtl/"],
  ["dozen", "tá (12 đơn vị)", "/ˈdʌzn/"],
  ["around", "khoảng, xấp xỉ", "/əˈraʊnd/"],
  ["zero", "số không", "/ˈzɪrəʊ/"],
  ["hundred", "một trăm", "/ˈhʌndrəd/"],
  ["thousand", "một nghìn, một ngàn", "/ˈθaʊznd/"],
  ["million", "một triệu", "/ˈmɪljən/"],
  ["billion", "một tỷ", "/ˈbɪljən/"],
  ["half", "một nửa", "/hæf/"],
  ["customer", "khách hàng", "/ˈkʌstəmər/"],
  ["cashier", "nhân viên thu ngân", "/kæˈʃɪr/"],
  ["attendant", "người phục vụ, nhân viên", "/əˈtendənt/"],
  ["manager", "giám đốc, quản lý", "/ˈmænɪdʒər/"],
  ["wallet", "cái bóp, ví tiền", "/ˈwɑːlɪt/"],
  ["purse", "túi cầm tay", "/pɜːrs/"],
  ["scale", "cái cân", "/skeɪl/"],
  ["counter", "quầy hàng", "/ˈkaʊntər/"],
  ["barcode reader", "máy đọc mã vạch", "None"],
  ["receipt", "biên lai, biên nhận", "/rɪˈsiːt/"],
  ["pay", "trả tiền, trả công", "/peɪ/"],
  ["expensive", "đắt tiền, tốn kém", "/ɪkˈspensɪv/"],
  ["cheap", "rẻ, không đắt", "/tʃiːp/"],
  ["discount", "chiết khấu, giảm giá", "/ˈdɪskaʊnt/"],
  ["sell", "có bán, bày bán", "/sel/"],
  ["price", "giá, giá cả", "/praɪs/"],
  ["trolley", "xe đẩy", "/ˈtrɑːli/"],
  ["credit card", "thẻ tín dụng", "/ˈkredɪt kɑːrd/"],
  ["cash", "tiền mặt", "/kæʃ/"],
  ["shop", "cửa hàng", "/ʃɑːp/"],
  ["money", "tiền", "/ˈmʌni/"],
  ["basket", "cái rổ, giỏ", "/ˈbæskɪt/"],
  ["bag", "túi, giỏ", "/bæɡ/"],
  ["buy", "mua", "/baɪ/"],
  ["greengrocer", "cửa hàng bán rau quả", "/ˈɡriːnɡrəʊsər/"],
  ["house-wares", "đồ gia dụng", "None"],
  ["toy store", "cửa hàng đồ chơi", "None"],
  ["shopping mall", "trung tâm mua sắm", "/ˈʃɑːpɪŋ mɔːl/"],
  ["grocery store", "cửa hàng tạp hóa", "None"],
  ["convenience store", "cửa hàng tiện lợi", "/kənˈviːniəns stɔːr/"],
  ["bargain", "mặc cả, thương lượng", "/ˈbɑːrɡən/"],
  ["refund", "hoàn lại, trả lại", "/ˈriːfʌnd/"],
  ["brochure", "tập quảng cáo", "/brəʊˈʃʊr/"],
  ["liquor store", "quán rượu", "/ˈlɪkər stɔːr/"],
  ["drugstore", "nhà thuốc", "/ˈdrʌɡstɔːr/"],
  ["candy store", "cửa hàng bánh kẹo", "None"],
  ["gift shop", "cửa hàng đồ lưu niệm", "/ˈɡɪft ʃɑːp/"],
  ["pet shop", "cửa hàng thú cưng", "None"],
  ["shoe shop", "cửa hàng giày dép", "None"],
  ["meat shop", "cửa hàng thịt", "None"],
  ["florist", "người bán hoa", "/ˈflɔːrɪst/"],
  ["butcher", "người bán thịt", "/ˈbʊtʃər/"],
  ["lamp", "đèn", "/læmp/"],
  ["pillowcase", "áo gối, bao gối", "/ˈpɪləʊkeɪs/"],
  ["curtain", "tầm rèm che", "/ˈkɜːrtn/"],
  ["bed", "cái giường", "/bed/"],
  ["mirror", "cái gương", "/ˈmɪrər/"],
  ["cushion", "đệm ngồi", "/ˈkʊʃn/"],
  ["wardrobe", "tủ đứng (chứa quần áo)", "/ˈwɔːrdrəʊb/"],
  ["fitted carpet", "thảm lót sàn", "/ˌfɪtɪd ˈkɑːrpɪt/"],
  ["dressing table", "bàn trang điểm", "/ˈdresɪŋ teɪbl/"],
  ["wallpaper", "giấy dán tường", "/ˈwɔːlpeɪpər/"],
  ["pillow", "gối ngủ", "/ˈpɪləʊ/"],
  ["carpet", "tấm thảm", "/ˈkɑːrpɪt/"],
  ["blind", "mành, rèm che", "/blaɪnd/"],
  ["mattress", "(tấm) nệm", "/ˈmætrəs/"],
  ["bedspread", "khăn trải giường", "/ˈbedspred/"],
  ["blanket", "tấm chăn, mền", "/ˈblæŋkɪt/"],
  ["jewellery", "trang sức, nữ trang", "/ˈdʒuːəlri/"],
  ["alarm clock", "đồng hồ báo thức", "/əˈlɑːrm klɑːk/"],
  ["air conditioner", "máy lạnh, điều hòa", "/ˈer kəndɪʃənər/"],
  ["box spring", "khung lò xo nâng nệm", "/ˈbɑːks sprɪŋ/"],
  ["comforter", "chăn lông", "/ˈkʌmfərtər/"],
  ["hanger", "móc treo (quần áo)", "/ˈhæŋər/"],
  ["closet", "tủ quần áo (âm tường)", "/ˈklɑːzɪt/"],
  ["comb", "cái lược", "/kəʊm/"],
  ["lightswitch", "công tắc điện", "None"],
  ["chest of drawers", "tủ kéo, tủ ngăn (đựng quần áo)", "/ˌtʃest əv ˈdrɔːrz/"],
  ["classmate", "bạn cùng lớp, bạn học", "/ˈklæsmeɪt/"],
  ["schoolmate", "bạn học, bạn cùng trường", "/ˈskuːlmeɪt/"],
  ["roommate", "bạn cùng phòng", "None"],
  ["soulmate", "bạn tâm giao, tri kỉ", "/ˈsəʊlmeɪt/"],
  ["colleague", "đồng nghiệp, cộng sự", "/ˈkɑːliːɡ/"],
  ["comradeship", "tình bạn, tình đồng chí", "/ˈkɑːmrædʃɪp/"],
  ["partner", "cộng sự, đồng đội", "/ˈpɑːrtnər/"],
  [
    "associate",
    "bạn đồng liêu, người cùng cộng tác; đồng minh",
    "/əˈsəʊsieɪt/",
  ],
  ["buddy", "bạn thân", "/ˈbʌdi/"],
  ["ally", "đồng minh", "/ˈælaɪ/"],
  ["companion", "bạn đồng hành", "/kəmˈpænjən/"],
  ["boyfriend", "bạn trai, người yêu", "/ˈbɔɪfrend/"],
  ["girlfriend", "bạn gái, người yêu", "/ˈɡɜːrlfrend/"],
  ["best friend", "bạn thân", "None"],
  ["pal", "bạn", "/pæl/"],
  ["friendship", "tình bạn", "/ˈfrendʃɪp/"],
  ["close", "(quan hệ) thân thiết", "None"],
  ["dishwasher", "máy rửa chén", "/ˈdɪʃwɔːʃər/"],
  ["dish drainer", "kệ úp chén bát", "None"],
  ["steamer", "chõ hấp, nồi hấp", "/ˈstiːmər/"],
  ["colander", "cái chao (dụng cụ nhà bếp)", "/ˈkɑːləndər/"],
  ["lid", "nắp, vung", "/lɪd/"],
  ["blender", "máy xay sinh tố", "/ˈblendər/"],
  ["pot", "nồi, xoong", "/pɑːt/"],
  ["toaster", "máy nướng bánh mì", "/ˈtəʊstər/"],
  ["dishtowel", "khăn lau chén bát", "/ˈdɪʃtaʊəl/"],
  ["refrigerator", "tủ lạnh", "/rɪˈfrɪdʒəreɪtər/"],
  ["freezer", "tủ đông", "/ˈfriːzər/"],
  ["cabinet", "tủ (có nhiều ngăn)", "/ˈkæbɪnət/"],
  ["microwave", "lò vi ba, lò vi sóng", "/ˈmaɪkrəweɪv/"],
  ["bowl", "(đo lường) bát, chén", "/bəʊl/"],
  ["cutting board", "thớt", "/ˈkʌtɪŋ bɔːrd/"],
  ["burner", "(bếp) lò đốt", "/ˈbɜːrnər/"],
  ["stove", "bếp lò", "/stəʊv/"],
  ["coffee maker", "máy pha cà phê", "/ˈkɔːfi meɪkər/"],
  ["oven", "lò, lò nướng", "/ˈʌvn/"],
  ["oven cleaner", "nước tẩy rửa lò", "None"],
  ["jar", "lọ, hũ", "/dʒɑːr/"],
  ["sink", "bồn rửa bát", "/sɪŋk/"],
  ["dish", "đĩa đựng thức ăn", "/dɪʃ/"],
  ["dish rack", "khay để ráo chén đĩa", "None"],
  ["sponge", "miếng xốp, bọt biển", "/spʌndʒ/"],
  ["chopstick", "đũa ăn", "/ˈtʃɑːpstɪk/"],
  ["pan", "chảo", "/pæn/"],
  ["cooker", "bếp nấu", "/ˈkʊkər/"],
  ["mug", "(đo lường) ca, cốc lớn", "/mʌɡ/"],
  ["kettle", "ấm đun nước", "/ˈketl/"],
  ["glass", "(đo lường) ly, cốc", "/ɡlæs/"],
  ["teapot", "bình trà, ấm pha trà", "/ˈtiːpɑːt/"],
  ["grill", "nướng (than)", "/ɡrɪl/"],
  ["tray", "cái khay, cái mâm", "/treɪ/"],
  ["whisk", "cái phới; máy đánh (trứng)", "/wɪsk/"],
  ["knife", "con dao", "/naɪf/"],
  ["spoon", "muỗng, thìa", "/spuːn/"],
  ["pendant", "mặt dây chuyền", "/ˈpendənt/"],
  ["earring", "bông tai, hoa tai", "/ˈɪrɪŋ/"],
  ["necklace", "vòng cổ, dây chuyền", "/ˈnekləs/"],
  ["bracelet", "vòng tay", "/ˈbreɪslət/"],
  ["brooch", "ghim cài áo, trâm cài", "/brəʊtʃ/"],
  ["hair clip", "kẹp tóc", "None"],
  ["wedding ring", "nhẫn cưới", "/ˈwedɪŋ rɪŋ/"],
  ["jeweler", "thợ kim hoàn", "None"],
  ["jewelry store", "cửa hàng trang sức, tiệm đá quý", "None"],
  ["anklet", "vòng chân", "/ˈæŋklət/"],
  ["noble", "đáng nể, ấn tượng", "/ˈnəʊbl/"],
  ["luxurious", "sang trọng, xa hoa", "/lʌɡˈʒʊriəs/"],
  ["modern", "hiện đại, tân tiến", "/ˈmɑːdərn/"],
  ["suitable", "phù hợp, thích hợp", "/ˈsuːtəbl/"],
  ["twinkle", "(sáng) lấp lánh", "/ˈtwɪŋkl/"],
  ["bead", "(chuỗi) hạt", "/biːd/"],
  ["hair tie", "dây buộc tóc", "None"],
  ["pocket watch", "đồng hồ bỏ túi, đồng hồ quả quýt", "None"],
  ["tiepin", "ghim cà vạt, kẹp cà vạt", "/ˈtaɪpɪn/"],
  ["precious stone", "đá quý", "/ˌpreʃəs ˈstəʊn/"],
  ["land", "đất, đất đai", "/lænd/"],
  ["pollute", "gây ô nhiễm", "/pəˈluːt/"],
  ["decompose", "thối rữa, phân hủy", "/ˌdiːkəmˈpəʊz/"],
  ["balance", "(trạng thái) cân bằng", "/ˈbæləns/"],
  ["climate change", "biến đổi khí hậu", "/ˈklaɪmət tʃeɪndʒ/"],
  ["global warming", "(hiện tượng) ấm lên toàn cầu", "/ˌɡləʊbl ˈwɔːrmɪŋ/"],
  ["oil slick", "dầu loang", "/ˈɔɪl slɪk/"],
  ["ozone layer", "tầng ozon", "/ˈəʊzəʊn ler/"],
  ["biodiversity", "đa dạng sinh học", "/ˌbaɪəʊdaɪˈvɜːrsəti/"],
  ["ecology", "hệ sinh thái; sinh thái học", "/iˈkɑːlədʒi/"],
  ["water", "nước", "/ˈwɔːtər/"],
  ["air", "khí, không khí", "/er/"],
  ["forest", "rừng, khu rừng", "/ˈfɔːrɪst/"],
  ["flora", "(hệ) thực vật", "/ˈflɔːrə/"],
  ["creature", "sinh vật", "/ˈkriːtʃər/"],
  ["insect", "(loài) côn trùng", "/ˈɪnsekt/"],
  ["reproduction", "(quá trình) sinh sản", "/ˌriːprəˈdʌkʃn/"],
  ["wildlife", "động vật hoang dã", "/ˈwaɪldlaɪf/"],
  ["sewage", "nước thải", "/ˈsuːɪdʒ/"],
  ["fauna", "(hệ) động vật", "/ˈfɔːnə/"],
  ["drapes", "màn cửa", "None"],
  ["cushion", "đệm ngồi", "/ˈkʊʃn/"],
  ["sofa", "sa-lông, ghế sô-pha, ghế nệm", "/ˈsəʊfə/"],
  ["rug", "tấm thảm", "/rʌɡ/"],
  ["banister", "thành cầu thang", "/ˈbænɪstər/"],
  ["bookcase", "tủ sách", "/ˈbʊkkeɪs/"],
  ["ceiling", "trần nhà", "/ˈsiːlɪŋ/"],
  ["clock", "đồng hồ", "/klɑːk/"],
  ["desk", "bàn học, bàn làm việc", "/desk/"],
  ["frame", "khung (ảnh, cửa,...)", "/freɪm/"],
  ["lampshade", "cái chụp đèn", "/ˈlæmpʃeɪd/"],
  ["mantelpiece", "bệ lò sưởi", "/ˈmæntlpiːs/"],
  ["painting", "bức tranh", "/ˈpeɪntɪŋ/"],
  ["remote control", "thiết bị điều khiển từ xa", "/rɪˌməʊt kənˈtrəʊl/"],
  ["speaker", "loa", "/ˈspiːkər/"],
  ["step", "bậc thang", "/step/"],
  ["stereo system", "dàn máy hát (có loa)", "None"],
  ["stereo", "máy xtê-rê-ô", "/ˈsteriəʊ/"],
  ["television", "vô tuyến, TV", "/ˈtelɪvɪʒn/"],
  ["vase", "cái bình, lọ hoa", "/veɪs/"],
  ["wall unit", "tủ kệ", "None"],
  ["lamp", "đèn", "/læmp/"],
  ["calendar", "(tấm) lịch", "/ˈkælɪndər/"],
  ["fan", "cái quạt", "/fæn/"],
  ["chair", "cái ghế", "/tʃer/"],
  ["stool", "ghế đẩu", "/stuːl/"],
  ["ashtray", "đồ gạt tàn thuốc", "/ˈæʃtreɪ/"],
  ["bookshelf", "kệ sách", "/ˈbʊkʃelf/"],
  ["fuse", "cầu chì", "/fjuːz/"],
  ["switch", "công tắc", "/swɪtʃ/"],
  ["couch", "ghế sa lông, ghế sô pha", "/kaʊtʃ/"],
  ["curtain", "rèm (cửa sổ)", "/ˈkɜːrtn/"],
  ["radiologist", "bác sĩ chụp X-quang", "/ˌreɪdiˈɑːlədʒɪst/"],
  ["emergency room", "phòng cấp cứu", "/ɪˈmɜːrdʒənsi ruːm/"],
  ["obstetrician", "bác sĩ sản khoa", "/ˌɑːbstəˈtrɪʃn/"],
  ["operating room", "phòng phẫu thuật", "None"],
  ["needle", "kim tiêm", "/ˈniːdl/"],
  ["laboratory", "phòng thí nghiệm", "/ˈlæbrətɔːri/"],
  ["pharmacy", "hiệu thuốc, nhà thuốc", "/ˈfɑːrməsi/"],
  ["hospital bed", "giường bệnh", "None"],
  ["call button", "chuông gọi (y tá)", "None"],
  ["doctor", "bác sĩ", "/ˈdɑːktər/"],
  ["nurse", "y tá", "/nɜːrs/"],
  ["gurney", "xe cáng, giường cấp cứu", "/ˈɡɜːrni/"],
  ["waiting room", "phòng chờ, khu vực ngồi chờ", "/ˈweɪtɪŋ ruːm/"],
  ["surgeon", "bác sĩ phẫu thuật", "/ˈsɜːrdʒən/"],
  ["midwife", "hộ sinh, bà đỡ", "/ˈmɪdwaɪf/"],
  ["injection", "(việc) tiêm thuốc", "/ɪnˈdʒekʃn/"],
  ["calcium", "(nguyên tố) canxi", "/ˈkælsiəm/"],
  ["hospital", "bệnh viện, nhà thương", "/ˈhɑːspɪtl/"],
  ["crutch", "cái nạng", "/krʌtʃ/"],
  ["wheelchair", "xe lăn", "/ˈwiːltʃer/"],
  ["paramedic", "nhân viên y tế, hộ lý", "/ˌpærəˈmedɪk/"],
  ["stretcher", "cáng cứu thương", "/ˈstretʃər/"],
  ["rush", "đưa đi, chuyển đi (nhanh)", "/rʌʃ/"],
  ["treat", "điều trị, chữa trị", "/triːt/"],
  ["condition", "trạng thái, tình trạng", "/kənˈdɪʃn/"],
  ["recovery", "sự bình phục, phục hồi", "/rɪˈkʌvəri/"],
  ["suffer", "bị, chịu", "/ˈsʌfər/"],
  ["deteriorate", "xấu đi, tệ hơn", "/dɪˈtɪriəreɪt/"],
  ["coma", "(tình trạng) hôn mê", "/ˈkəʊmə/"],
  ["common cold", "(bệnh) cảm lạnh thông thường", "None"],
  ["monitor", "(máy tính) màn hình", "/ˈmɑːnɪtər/"],
  ["mouse pad", "tấm lót chuột", "None"],
  ["printer", "máy in", "/ˈprɪntər/"],
  ["scanner", "máy quét", "/ˈskænər/"],
  ["open", "(tin học) khởi động, mở", "/ˈəʊpən/"],
  ["close", "(tin học) đóng, tắt", "None"],
  ["delete", "xóa, loại bỏ", "/dɪˈliːt/"],
  ["insert", "cho vào, nhét vào", "/ɪnˈsɜːrt/"],
  ["merge", "sát nhập, hợp nhất", "/mɜːrdʒ/"],
  ["helpline", "đường dây trợ giúp", "/ˈhelplaɪn/"],
  ["hard disk", "(tin học) ổ cứng", "/ˈhɑːrd dɪsk/"],
  ["software", "(tin học) phần mềm", "/ˈsɔːftwer/"],
  ["CD-ROM", "(tin học) đĩa CD dữ liệu", "None"],
  ["toolbar", "(tin học) thanh công cụ", "/ˈtuːlbɑːr/"],
  ["database", "(tin học) cơ sở dữ liệu", "/ˈdeɪtəbeɪs/"],
  ["hacker", "tin tặc", "/ˈhækər/"],
  ["save as", "(tin học) lưu với định dạng", "None"],
  ["select", "(tin học) chọn, nhấn chọn", "/sɪˈlekt/"],
  ["copy", "(tin học) sao chép", "/ˈkɑːpi/"],
  ["computer", "máy vi tính", "/kəmˈpjuːtər/"],
  ["laptop", "máy tính xách tay", "/ˈlæptɑːp/"],
  ["speaker", "loa", "/ˈspiːkər/"],
  ["file", "(tin học) tệp, tập tin", "/faɪl/"],
  ["disk drive", "(tin học) ổ đĩa", "/ˈdɪsk draɪv/"],
  ["battery", "pin", "/ˈbætəri/"],
  ["click", "(tin học) nhấp chuột", "/klɪk/"],
  ["type", "đánh chữ, gõ chữ", "/taɪp/"],
  ["mouse", "(máy tính) con chuột", "/maʊs/"],
  ["keyboard", "(máy tính) bàn phím", "/ˈkiːbɔːrd/"],
  ["mouse mat", "miếng lót chuột", "/ˈmaʊs mæt/"],
  ["key", "(tin học) phím", "/kiː/"],
  ["shut down", "đóng cửa; tắt máy", "None"],
  ["folder", "(tin học) thư mục", "/ˈfəʊldər/"],
  ["print", "in (trên giấy)", "/prɪnt/"],
  ["program", "(tin học) chương trình", "/ˈprəʊɡræm/"],
  ["search", "(tin học) tìm kiếm thông tin", "/sɜːrtʃ/"],
  ["screen", "màn hình (TV, máy tính)", "/skriːn/"],
  ["dusting", "(việc) quét bụi", "None"],
  ["cooking", "(việc) nấu ăn", "/ˈkʊkɪŋ/"],
  ["ironing", "(việc) ủi đồ, là đồ", "/ˈaɪərnɪŋ/"],
  ["sweep", "quét dọn (phòng)", "/swiːp/"],
  ["wipe", "chùi, lau sạch", "/waɪp/"],
  ["throw out", "vứt, bỏ đi", "None"],
  ["vacuum", "hút bụi", "/ˈvækjuːm/"],
  ["cleaning", "(việc) dọn dẹp", "/ˈkliːnɪŋ/"],
  ["polish", "đánh bóng", "/ˈpɑːlɪʃ/"],
  ["fold", "gấp gọn, gập lại", "/fəʊld/"],
  ["scrub", "chà, cọ rửa", "/skrʌb/"],
  ["tighten", "thắt, vặn (chặt)", "/ˈtaɪtn/"],
  ["hang out", "phơi đồ (ngoài trời)", "None"],
  ["make the bed", "dọn giường, gấp chăn mền", "None"],
  ["set the table", "bày chén bát (bàn ăn)", "None"],
  ["clear the table", "dọn dẹp chén bát (trên bàn)", "None"],
  ["mow the lawn", "cắt cỏ", "None"],
  ["dishwashing", "(việc) rửa chén, rửa bát", "None"],
  ["water the plants", "tưới cây", "None"],
  ["clean the kitchen", "lau dọn bếp", "None"],
  ["play", "vở kịch", "/pleɪ/"],
  ["circus", "rạp xiếc, vở xiếc", "/ˈsɜːrkəs/"],
  ["stadium", "sân vận động", "/ˈsteɪdiəm/"],
  ["orchestra", "ban nhạc, dàn nhạc", "/ˈɔːrkɪstrə/"],
  ["scene", "cảnh, phân cảnh", "/siːn/"],
  ["opera", "nhạc kịch, ô-pê-ra", "/ˈɑːprə/"],
  ["theater", "rạp hát, nhà hát", "None"],
  ["applaud", "vỗ tay (tán thưởng)", "/əˈplɔːd/"],
  ["perform", "trình diễn, biểu diễn", "/pərˈfɔːrm/"],
  ["exhibit", "vật triển lãm, bộ sưu tập", "/ɪɡˈzɪbɪt/"],
  ["art gallery", "phòng tranh, khu triển lãm", "/ˈɑːrt ɡæləri/"],
  ["comedy", "(thể loại) hài kịch", "/ˈkɑːmədi/"],
  ["chamber music", "nhạc thính phòng", "/ˈtʃeɪmbər mjuːzɪk/"],
  ["disco", "sàn nhảy, câu lạc bộ", "/ˈdɪskəʊ/"],
  ["casino", "sòng bạc", "/kəˈsiːnəʊ/"],
  ["pub", "quán rượu", "/pʌb/"],
  ["concert hall", "nhà hát", "None"],
  ["venue", "địa điểm (tổ chức)", "/ˈvenjuː/"],
  ["travel", "đi, du lịch", "/ˈtrævl/"],
  ["travel agent", "đại lý du lịch", "/ˈtrævl eɪdʒənt/"],
  ["vacation", "kỳ nghỉ", "/veɪˈkeɪʃn/"],
  ["flight", "chuyến bay", "/flaɪt/"],
  ["voyage", "chuyến đi, chuyến hải hành", "/ˈvɔɪɪdʒ/"],
  ["relax", "thư giãn, nghỉ xả hơi", "/rɪˈlæks/"],
  ["cancel", "hủy bỏ (kế hoạch)", "/ˈkænsl/"],
  ["homestay", "(dịch vụ) lưu trú tại nhà dân bản địa", "/ˈhəʊmsteɪ/"],
  ["souvenir", "quà lưu niệm", "/ˌsuːvəˈnɪr/"],
  ["travel sickness", "(chứng) say tàu xe", "/ˈtrævl sɪknəs/"],
  ["journey", "hành trình, chuyến đi", "/ˈdʒɜːrni/"],
  ["peak season", "(du lịch) mùa cao điểm", "None"],
  ["route", "lộ trình, tuyến đường", "/ruːt/"],
  ["trip", "chuyến đi (ngắn ngày)", "/trɪp/"],
  ["excursion", "chuyến đi, chuyến tham quan", "/ɪkˈskɜːrʒn/"],
  ["luggage", "hành lí", "/ˈlʌɡɪdʒ/"],
  ["tourist", "du khách", "/ˈtʊrɪst/"],
  ["ticket", "vé", "/ˈtɪkɪt/"],
  ["eager", "háo hức, hăm hở", "/ˈiːɡər/"],
  ["sunglasses", "kính mát, kính râm", "/ˈsʌnɡlæsɪz/"],
  ["safari", "chuyến thám hiểm thiên nhiên", "/səˈfɑːri/"],
  ["village", "ngôi làng", "/ˈvɪlɪdʒ/"],
  ["countryside", "nông thôn, miền quê", "/ˈkʌntrisaɪd/"],
  ["isolated", "riêng, duy nhất", "/ˈaɪsəleɪtɪd/"],
  ["cottage", "nhà tranh, nhà ở vùng quê", "/ˈkɑːtɪdʒ/"],
  ["winding", "quanh co, uốn khúc, khúc khuỷu", "/ˈwaɪndɪŋ/"],
  ["well", "cái giếng", "/wel/"],
  ["buffalo", "con trâu", "/ˈbʌfələʊ/"],
  ["field", "cánh đồng", "/fiːld/"],
  ["canal", "kênh, rạch", "/kəˈnæl/"],
  ["river", "sông", "/ˈrɪvər/"],
  ["pond", "cái ao", "/pɑːnd/"],
  ["folk music", "nhạc dân gian", "/ˈfəʊk mjuːzɪk/"],
  ["farm", "trang trại", "/fɑːrm/"],
  ["plow", "cày, xới", "/plaʊ/"],
  ["agriculture", "nông nghiệp", "/ˈæɡrɪkʌltʃər/"],
  ["boat", "thuyền, tàu", "/bəʊt/"],
  ["peaceful", "yên bình", "/ˈpiːsfl/"],
  ["bay", "vịnh", "/beɪ/"],
  ["hill", "ngọn đồi", "/hɪl/"],
  ["forest", "rừng, khu rừng", "/ˈfɔːrɪst/"],
  ["mountain", "núi", "/ˈmaʊntn/"],
  ["port", "bến cảng", "/pɔːrt/"],
  ["lake", "hồ", "/leɪk/"],
  ["sea", "biển", "/siː/"],
  ["sand", "cát, hạt cát", "/sænd/"],
  ["valley", "thung lũng", "/ˈvæli/"],
  ["waterfall", "thác nước", "/ˈwɔːtərfɔːl/"],
  ["barn", "kho thóc", "/bɑːrn/"],
  ["harvest", "mùa màng, sản lượng thu hoạch", "/ˈhɑːrvɪst/"],
  ["cattle", "gia súc", "/ˈkætl/"],
  ["rural", "(thuộc) nông thôn, thôn dã", "/ˈrʊrəl/"],
  ["cliff", "vách đá (nhô ra biển)", "/klɪf/"],
  ["landscape", "phong cảnh, khung cảnh", "/ˈlændskeɪp/"],
  ["terraced house", "nhà phố, nhà liên kế", "/ˌterəst ˈhaʊs/"],
  ["view", "khung cảnh, quang cảnh", "/vjuː/"],
  ["Mid-Autumn Festival", "Tết Trung thu", "None"],
  ["moon", "trăng, vầng trăng", "/muːn/"],
  ["cake", "bánh ngọt, bánh nướng", "/keɪk/"],
  ["toy", "món đồ chơi", "/tɔɪ/"],
  ["mask", "mặt nạ", "/mæsk/"],
  ["banyan", "cây đa", "/ˈbænjən/"],
  ["lantern", "lồng đèn", "/ˈlæntərn/"],
  ["bamboo", "(cây) tre", "/ˌbæmˈbuː/"],
  ["perform", "trình diễn, biểu diễn", "/pərˈfɔːrm/"],
  ["celebrate", "làm lễ ăn mừng, kỷ niệm", "/ˈselɪbreɪt/"],
  ["family reunion", "họp mặt gia đình", "None"],
  ["rabbit", "(loài) thỏ", "/ˈræbɪt/"],
  ["bride", "cô dâu", "/braɪd/"],
  ["vow", "lời thề, lời đính ước", "/vaʊ/"],
  ["best man", "phù rể, rể phụ", "/ˌbest ˈmæn/"],
  ["groom", "chú rể", "/ɡruːm/"],
  ["tuxedo", "áo xmốc-king", "/tʌkˈsiːdəʊ/"],
  ["party", "tiệc, bữa tiệc", "/ˈpɑːrti/"],
  ["wedding", "lễ cưới, đám cưới", "/ˈwedɪŋ/"],
  ["wedding card", "thiệp mời đám cưới", "None"],
  ["reception", "tiệc chiêu đãi", "/rɪˈsepʃn/"],
  ["champagne", "(rượu) sâm panh", "/ʃæmˈpeɪn/"],
  ["bouquet", "bó hoa", "/buˈkeɪ/"],
  ["married", "đã kết hôn", "/ˈmærid/"],
  ["newlywed", "(vợ chồng) mới cưới", "None"],
  ["cake", "bánh ngọt, bánh nướng", "/keɪk/"],
  ["ring", "nhẫn", "None"],
  ["emblem", "biểu tượng", "/ˈembləm/"],
  ["band", "ban nhạc", "/bænd/"],
  ["congratulation", "lời chúc mừng", "/kənˌɡrætʃəˈleɪʃn/"],
  ["jewelry", "nữ trang, trang sức", "None"],
  ["wine", "rượu vang", "/waɪn/"],
  ["dowry", "của hồi môn", "/ˈdaʊri/"],
  ["honeymoon", "tuần trăng mật", "/ˈhʌnimuːn/"],
  ["anniversary", "ngày kỷ niệm", "/ˌænɪˈvɜːrsəri/"],
  ["brother-in-law", "anh/em rể, anh/em chồng, anh/em vợ", "/ˈbrʌðər ɪn lɔː/"],
  ["sister-in-law", "chị/em dâu, chị/em chồng, chị/em vợ", "/ˈsɪstər ɪn lɔː/"],
  ["engaged", "đã đính ước, hứa hôn", "/ɪnˈɡeɪdʒd/"],
  ["couple", "cặp đôi, đôi vợ chồng", "/ˈkʌpl/"],
  ["husband", "chồng", "/ˈhʌzbənd/"],
  ["wife", "vợ", "/waɪf/"],
  ["ceremony", "nghi lễ, nghi thức", "/ˈserəməʊni/"],
  ["betroth", "hứa hôn, đính hôn", "None"],
  ["aboard", "đi lên, ở trên (phương tiện)", "/əˈbɔːrd/"],
  ["switch off", "tắt", "None"],
  ["lavatory", "bồn cầu, phòng vệ sinh", "/ˈlævətɔːri/"],
  ["blanket", "tấm chăn, mền", "/ˈblæŋkɪt/"],
  ["oxygen mask", "mặt nạ thở oxy", "/ˈɑːksɪdʒən mæsk/"],
  ["serve", "phục vụ (thức ăn)", "/sɜːrv/"],
  ["window seat", "ghế cạnh cửa sổ", "/ˈwɪndəʊ siːt/"],
  ["airsick", "(bị) say máy bay", "/ˈersɪk/"],
  ["cockpit", "buồng lái", "/ˈkɑːkpɪt/"],
  ["fasten", "thắt, buộc", "/ˈfæsn/"],
  ["take off", "cất cánh", "None"],
  ["co-pilot", "phi công phụ, lái phụ", "/ˈkəʊ paɪlət/"],
  ["assist", "hỗ trợ, giúp đỡ", "/əˈsɪst/"],
  ["first-class", "(ghế) hạng nhất", "/ˌfɜːrst ˈklæs/"],
  ["confiscate", "tịch thu", "/ˈkɑːnfɪskeɪt/"],
  ["turn on", "bật, mở", "None"],
  ["bruise", "vết thâm, vết bầm", "/bruːz/"],
  ["diet", "chế độ ăn kiêng; thời gian ăn kiêng", "/ˈdaɪət/"],
  ["medicine", "thuốc, dược phẩm (dạng lỏng)", "/ˈmedɪsn/"],
  ["scratch", "cào, làm xước", "/skrætʃ/"],
  ["fitness", "thể lực, sức khỏe", "/ˈfɪtnəs/"],
  ["malnutrition", "(tình trạng) suy dinh dưỡng", "/ˌmælnuˈtrɪʃn/"],
  ["blood pressure", "huyết áp", "/ˈblʌd preʃər/"],
  ["cavity", "(lỗ) sâu răng", "/ˈkævəti/"],
  ["lose weight", "giảm cân", "None"],
  ["flu", "(bệnh) cảm cúm", "/fluː/"],
  ["appetite", "(cảm giác) thèm ăn", "/ˈæpɪtaɪt/"],
  ["operation", "ca mổ, ca phẫu thuật", "/ˌɑːpəˈreɪʃn/"],
  ["cough", "cơn ho, cái ho", "/kɔːf/"],
  ["diarrhea", "(bệnh) tiêu chảy", "None"],
  ["fever", "(bệnh) sốt", "/ˈfiːvər/"],
  ["headache", "(bệnh) đau đầu", "/ˈhedeɪk/"],
  ["pill", "viên thuốc con nhộng", "/pɪl/"],
  ["tranquilizer", "thuốc an thần", "None"],
  ["earache", "(bệnh) đau tai", "/ˈɪreɪk/"],
  ["corn", "bắp, ngô", "/kɔːrn/"],
  ["onion", "củ hành, hành tây", "/ˈʌnjən/"],
  ["beet", "củ dền", "/biːt/"],
  ["red pepper", "ớt chuông đỏ", "/ˌred ˈpepər/"],
  ["sweet potato", "khoai lang", "/ˈswiːt pəteɪtəʊ/"],
  ["celery", "cần tây", "/ˈseləri/"],
  ["broccoli", "bông cải xanh", "/ˈbrɑːkəli/"],
  ["cauliflower", "súp lơ, bông cải", "/ˈkɑːliflaʊər/"],
  ["lettuce", "xà lách, rau diếp", "/ˈletɪs/"],
  ["cucumber", "dưa chuột, dưa leo", "/ˈkjuːkʌmbər/"],
  ["pea", "đậu Hà Lan", "/piː/"],
  ["eggplant", "quả cà tím", "/ˈeɡplænt/"],
  ["cabbage", "cải bắp", "/ˈkæbɪdʒ/"],
  ["carrot", "cà rốt, củ cải đỏ", "/ˈkærət/"],
  ["tomato", "cà chua", "/təˈmeɪtəʊ/"],
  ["mushroom", "nấm", "/ˈmʌʃrʊm/"],
  ["potato", "khoai tây", "/pəˈteɪtəʊ/"],
  ["garlic", "tỏi", "/ˈɡɑːrlɪk/"],
  ["butternut squash", "bí nghệ, bí hồ lô", "/ˌbʌtərnʌt ˈskwɑːʃ/"],
  ["artichoke", "atisô", "/ˈɑːrtɪtʃəʊk/"],
  ["seedless", "(trái cây) không hạt", "/ˈsiːdləs/"],
  ["bunch", "chùm, bó", "/bʌntʃ/"],
  ["turnip", "cải củ, củ cải tím", "/ˈtɜːrnɪp/"],
  ["shell", "vỏ, bao, mai", "/ʃel/"],
  ["bean", "đậu", "/biːn/"],
  ["zucchini", "quả bí ngòi", "/zuˈkiːni/"],
  ["pickled", "(thực phẩm) muối chua, ngâm giấm", "/ˈpɪkld/"],
  ["pepper", "tiêu, bột tiêu", "/ˈpepər/"],
  ["raw", "chưa chế biến, sống", "/rɔː/"],
  ["ripe", "(trái cây) chín", "/raɪp/"],
  ["citrus", "trái cây thuộc họ cam chanh", "/ˈsɪtrəs/"],
  ["rotten", "thối, hư", "/ˈrɑːtn/"],
  ["succulent", "mọng nước", "/ˈsʌkjələnt/"],
  ["taro", "củ khoai sọ, khoai môn", "None"],
  ["peanut", "đậu phộng", "/ˈpiːnʌt/"],
  ["ginger", "củ gừng", "/ˈdʒɪndʒər/"],
  ["green bean", "đậu cô ve, đậu xanh", "/ˌɡriːn ˈbiːn/"],
  ["transportation", "phương tiện (giao thông)", "/ˌtrænspərˈteɪʃn/"],
  ["boat", "thuyền, tàu", "/bəʊt/"],
  ["traffic light", "đèn giao thông, đèn tín hiệu", "/ˈtræfɪk laɪt/"],
  ["ship", "con tàu, con thuyền", "/ʃɪp/"],
  ["vehicle", "xe cộ, phương tiện (giao thông)", "/ˈviːəkl/"],
  ["van", "xe van, xe chở hàng loại nhỏ", "/væn/"],
  ["driver", "tài xế, người lái xe", "/ˈdraɪvər/"],
  ["police car", "xe cảnh sát", "None"],
  ["bus", "xe buýt", "/bʌs/"],
  ["car", "ô tô, xe hơi", "/kɑːr/"],
  ["train", "xe lửa, tàu hỏa", "/treɪn/"],
  ["motorbike", "xe gắn máy, xe phân khối lớn", "/ˈməʊtərbaɪk/"],
  ["bicycle", "xe đạp", "/ˈbaɪsɪkl/"],
  ["airplane", "máy bay", "/ˈerpleɪn/"],
  ["ambulance", "xe cứu thương", "/ˈæmbjələns/"],
  ["superhighway", "đường cao tốc (liên tỉnh)", "/ˌsuːpərˈhaɪweɪ/"],
  ["helmet", "nón bảo hiểm", "/ˈhelmɪt/"],
  ["cart", "xe ngựa, xe kéo", "/kɑːrt/"],
  ["get on", "lên (phương tiện)", "None"],
  ["get off", "xuống, rời khỏi (phương tiện)", "None"],
  ["line", "tuyến đường", "/laɪn/"],
  ["exit", "cửa ra, lối ra", "/ˈeksɪt/"],
  ["boulevard", "đại lộ", "/ˈbʊləvɑːrd/"],
  ["hovercraft", "tàu đệm khí", "/ˈhʌvərkræft/"],
  ["submarine", "tàu ngầm", "/ˌsʌbməˈriːn/"],
  ["scooter", "xe tay ga", "/ˈskuːtər/"],
  ["lorry", "xe tải", "/ˈlɔːri/"],
  ["intersection", "ngã tư, giao lộ", "/ˈɪntərsekʃn/"],
  ["track", "đường ray", "/træk/"],
  ["cruise ship", "du thuyền", "None"],
  ["subway", "tàu điện ngầm", "/ˈsʌbweɪ/"],
  ["tricycle", "xe đạp ba bánh", "/ˈtraɪsɪkl/"],
  ["pull over", "(phương tiện) tấp vào lề", "None"],
  ["rush hour", "giờ cao điểm", "/ˈrʌʃ aʊər/"],
  ["tram", "tàu điện", "/træm/"],
  ["motorized bicycle", "xe đạp điện, xe đạp động cơ", "None"],
  ["cable car", "cáp treo", "/ˈkeɪbl kɑːr/"],
  ["time", "thời gian, khoảng thời gian", "/taɪm/"],
  ["midnight", "nửa đêm", "/ˈmɪdnaɪt/"],
  ["hour", "giờ, tiếng đồng hồ", "/ˈaʊər/"],
  ["quarter", "quý", "/ˈkwɔːrtər/"],
  ['o"clock', "(đọc giờ) giờ đúng", "None"],
  ["weekday", "ngày trong tuần, ngày thường", "/ˈwiːkdeɪ/"],
  ["century", "thế kỷ, 100 năm", "/ˈsentʃəri/"],
  ["decade", "thập kỷ", "/ˈdekeɪd/"],
  ["evening", "buổi tối", "/ˈiːvnɪŋ/"],
  ["afternoon", "xế trưa, buổi chiều", "/ˌæftərˈnuːn/"],
  ["month", "tháng", "/mʌnθ/"],
  ["year", "năm", "/jɪr/"],
  ["date", "ngày (cụ thể)", "/deɪt/"],
  ["week", "bảy ngày, tuần", "/wiːk/"],
  ["weekend", "cuối tuần", "/ˈwiːkend/"],
  ["morning", "buổi sáng", "/ˈmɔːrnɪŋ/"],
  ["millennium", "thiên niên kỷ, 1.000 năm", "/mɪˈleniəm/"],
  ["in time", "vừa đúng lúc, vừa kịp lúc", "None"],
  ["night", "ban đêm, buổi tối", "/naɪt/"],
  ["fortnight", "hai tuần", "/ˈfɔːrtnaɪt/"],
  ["minute", "phút", "None"],
  ["soon", "sớm, nhanh", "/suːn/"],
  ["last", "kéo dài, có độ dài", "None"],
  ["later", "sau này, sau đó", "/ˈleɪtər/"],
  ["today", "hôm nay", "/təˈdeɪ/"],
  ["yesterday", "ngày hôm qua", "/ˈjestərdeɪ/"],
  ["tomorrow", "ngày mai", "/təˈmɑːrəʊ/"],
  ["run out", "cạn kiệt, hết", "None"],
  ["during", "suốt, trong suốt", "/ˈdʊrɪŋ/"],
  ["until", "cho đến, đến khi", "/ənˈtɪl/"],
  ["since", "từ đó, từ ấy", "/sɪns/"],
  ["off", "ra khỏi, đi khỏi", "/ɔːf/"],
  ["future", "tương lai, thời gian sắp tới", "/ˈfjuːtʃər/"],
  ["bedtime", "giờ đi ngủ, giờ ngủ", "/ˈbedtaɪm/"],
  ["stopwatch", "đồng hồ bấm giờ", "/ˈstɑːpwɑːtʃ/"],
  ["dawn", "bình minh, rạng đông", "/dɔːn/"],
  ["sunset", "hoàng hôn, tà dương", "/ˈsʌnset/"],
  ["all the time", "suốt, luôn", "None"],
  ["past", "(thời gian) quá khứ", "/pæst/"],
  ["bright", "thông minh, sáng dạ", "/braɪt/"],
  ["angry", "tức giận, cáu", "/ˈæŋɡri/"],
  ["angry with", "tức giận với", "None"],
  ["sleepy", "buồn ngủ", "/ˈsliːpi/"],
  ["surprised", "ngạc nhiên, bất ngờ", "/sərˈpraɪzd/"],
  ["grateful", "biết ơn, nhớ ơn", "/ˈɡreɪtfl/"],
  ["funny", "buồn cười, thú vị", "/ˈfʌni/"],
  ["scared", "sợ hãi, e ngại", "/skerd/"],
  ["embarrassed", "bối rối, xấu hổ", "/ɪmˈbærəst/"],
  ["confused", "lúng túng, bối rối", "/kənˈfjuːzd/"],
  ["sad", "buồn rầu", "/sæd/"],
  ["hungry", "đói bụng", "/ˈhʌŋɡri/"],
  ["happy", "vui, hạnh phúc", "/ˈhæpi/"],
  ["jealous", "(tình cảm) ghen, ghen tuông", "/ˈdʒeləs/"],
  ["nervous", "hồi hộp, bồn chồn, lo lắng", "/ˈnɜːrvəs/"],
  ["thirsty", "khát nước", "/ˈθɜːrsti/"],
  ["comfortable", "(cảm giác) thoải mái, dễ chịu", "/ˈkʌmftəbl/"],
  ["shame", "(cảm giác) xấu hổ, hổ thẹn", "/ʃeɪm/"],
  ["tense", "căng thẳng", "/tens/"],
  ["tired", "mệt mỏi, chán ngán", "/ˈtaɪərd/"],
  ["bored", "chán, nản", "/bɔːrd/"],
  ["reliable", "đáng tin cậy", "/rɪˈlaɪəbl/"],
  ["rude", "bất lịch sự, thô lỗ", "/ruːd/"],
  ["selfish", "ích kỷ", "/ˈselfɪʃ/"],
  ["sensitive", "nhạy cảm, dễ nóng giận", "/ˈsensətɪv/"],
  ["stubborn", "bướng bỉnh, cứng đầu", "/ˈstʌbərn/"],
  ["patient", "kiên nhẫn, nhẫn nại", "/ˈpeɪʃnt/"],
  ["humorous", "hài hước, vui nhộn", "/ˈhjuːmərəs/"],
  ["sincere", "chân thành, thành thật", "/sɪnˈsɪr/"],
  ["generous", "hào phóng, rộng rãi", "/ˈdʒenərəs/"],
  ["honest", "thành thật, thẳng thắn", "/ˈɑːnɪst/"],
  ["kind", "tử tế, tốt bụng", "/kaɪnd/"],
  ["loyal", "trung thành, chân thành", "/ˈlɔɪəl/"],
  ["modest", "khiêm tốn", "/ˈmɑːdɪst/"],
  ["nasty", "khó chịu, xấu tính", "/ˈnæsti/"],
  ["shy", "nhút nhát, bẽn lẽn", "/ʃaɪ/"],
  ["sociable", "dễ gần, hòa đồng", "/ˈsəʊʃəbl/"],
  ["reserved", "rụt rè, dè dặt", "/rɪˈzɜːrvd/"],
  ["confident", "tự tin", "/ˈkɑːnfɪdənt/"],
  ["pleasant", "lịch sự, hòa nhã", "/ˈpleznt/"],
  ["clever", "thông minh, sáng dạ", "/ˈklevər/"],
  ["thoughtful", "ân cần, chu đáo", "/ˈθɔːtfl/"],
  ["proud", "(xem trọng) tự tôn, thể diện", "/praʊd/"],
  ["lazy", "lười biếng", "/ˈleɪzi/"],
  ["crazy", "ngu ngốc, kỳ quái", "/ˈkreɪzi/"],
  ["silly", "ngớ ngẩn, ngốc nghếch", "/ˈsɪli/"],
  ["bossy", "hách dịch", "/ˈbɔːsi/"],
  ["gossip", "người mách lẻo", "/ˈɡɑːsɪp/"],
  ["extrovert", "người hướng ngoại", "/ˈekstrəvɜːrt/"],
  ["coward", "người hèn nhát", "/ˈkaʊərd/"],
  ["big-head", "người tự cao", "/ˈbɪɡ hed/"],
  ["snob", "người hợm hĩnh, người tự mãn", "/snɑːb/"],
  ["liar", "người nói dối", "/ˈlaɪər/"],
  ["ambitious", "tham vọng, có hoài bão", "/æmˈbɪʃəs/"],
  ["introvert", "người hướng nội", "/ˈɪntrəvɜːrt/"],
  ["stingy", "ích kỷ, keo kiệt", "/ˈstɪndʒi/"],
  ["arrogant", "kiêu căng, ngạo mạn", "/ˈærəɡənt/"],
  ["vain", "tự phụ, tự đắc", "/veɪn/"],
  ["absent-minded", "đãng trí, hay quên", "/ˌæbsənt ˈmaɪndɪd/"],
  ["hostile", "dữ tợn, thù địch", "/ˈhɑːstl/"],
  ["juice", "nước ép", "/dʒuːs/"],
  ["lemonade", "nước chanh", "/ˌleməˈneɪd/"],
  ["beer", "bia", "/bɪr/"],
  ["soda", "(món) sô-đa, nước ngọt", "/ˈsəʊdə/"],
  ["cider", "rượu táo", "/ˈsaɪdər/"],
  ["rum", "(rượu) rum", "/rʌm/"],
  ["ginger ale", "nước ngọt hương gừng", "/ˌdʒɪndʒər ˈeɪl/"],
  ["champagne", "(rượu) sâm panh", "/ʃæmˈpeɪn/"],
  ["bitter", "(vị) đắng", "/ˈbɪtər/"],
  ["malt", "mạch nha", "/mɔːlt/"],
  ["barley", "(cây) lúa mạch", "/ˈbɑːrli/"],
  ["distillery", "nhà máy rượu, xưởng rượu", "/dɪˈstɪləri/"],
  ["coffee", "(thức uống) cà phê", "/ˈkɔːfi/"],
  ["milk", "sữa", "/mɪlk/"],
  ["tea", "(thức uống) trà", "/tiː/"],
  ["red wine", "rượu vang đỏ", "/ˌred ˈwaɪn/"],
  ["non-alcoholic", "(thức uống) không cồn", "/ˌnɑːn ˌælkəˈhɑːlɪk/"],
  ["full-cream", "(sữa) béo, nguyên kem", "/ˌfʊl ˈkriːm/"],
  ["herbal", "(chứa) thảo mộc", "/ˈɜːrbl/"],
  ["mineral water", "nước khoáng", "/ˈmɪnərəl wɔːtər/"],
  ["lotus", "(cây) hoa sen", "/ˈləʊtəs/"],
  ["lily", "(hoa) ly, loa kèn", "/ˈlɪli/"],
  ["poppy", "(cây) anh túc", "/ˈpɑːpi/"],
  ["bougainvillea", "(cây) hoa giấy", "/ˌbuːɡənˈvɪliə/"],
  ["gerbera", "(cây) hoa đồng tiền", "None"],
  ["mimosa", "(cây) mắc cỡ, trinh nữ", "/mɪˈməʊzə/"],
  ["tuberose", "(hoa) huệ", "None"],
  ["apricot blossom", "(hoa) mai", "None"],
  ["dahlia", "(hoa) thược dược", "/ˈdeɪliə/"],
  ["jasmine", "(cây) hoa nhài, hoa lài", "/ˈdʒæzmɪn/"],
  ["sunflower", "(hoa) hướng dương", "/ˈsʌnflaʊər/"],
  ["marigold", "(hoa) cúc vạn thọ", "/ˈmærɪɡəʊld/"],
  ["orchid", "(cây) lan, phong lan", "/ˈɔːrkɪd/"],
  ["rose", "(hoa) hồng", "/rəʊz/"],
  ["carnation", "(hoa) cẩm chướng", "/kɑːrˈneɪʃn/"],
  ["cherry blossom", "(hoa) anh đào", "None"],
  ["poinsettia", "(cây) trạng nguyên", "/ˌpɔɪnˈsetiə/"],
  ["flamboyant", "(cây) phượng", "/flæmˈbɔɪənt/"],
  ["hibiscus", "(cây) bụt giấm, atisô đỏ", "/hɪˈbɪskəs/"],
  ["peach blossom", "(hoa) đào", "None"],
  ["movie", "phim, phim truyện", "/ˈmuːvi/"],
  ["famous", "nổi tiếng", "/ˈfeɪməs/"],
  ["comedy", "(thể loại) hài kịch", "/ˈkɑːmədi/"],
  ["audience", "khán giả, người xem", "/ˈɔːdiəns/"],
  ["Film Festival", "liên hoan phim", "None"],
  ["trailer", "(điện ảnh) đoạn phim quảng cáo", "/ˈtreɪlər/"],
  ["movie star", "ngôi sao (điện ảnh)", "/ˈmuːvi stɑːr/"],
  ["soundtrack", "nhạc phim", "/ˈsaʊndtræk/"],
  ["cartoon", "phim hoạt hình", "/kɑːrˈtuːn/"],
  ["drama", "vở kịch, phim truyền hình", "/ˈdrɑːmə/"],
  ["action film", "phim hành động", "/ˈækʃn fɪlm/"],
  ["action", "sự việc thú vị, yếu tố kịch tính", "/ˈækʃn/"],
  ["celebrity", "người nổi tiếng", "/səˈlebrəti/"],
  ["script", "kịch bản", "/skrɪpt/"],
  ["theater", "rạp hát, nhà hát", "None"],
  ["actor", "diễn viên; nam diễn viên", "/ˈæktər/"],
  ["actress", "nữ diễn viên", "/ˈæktrəs/"],
  ["director", "đạo diễn", "/dəˈrektər/"],
  ["romantic", "(thuộc) tình cảm, lãng mạn", "/rəʊˈmæntɪk/"],
  ["silent film", "phim câm", "None"],
  ["movie ticket", "vé xem phim", "None"],
  ["stadium", "sân vận động", "/ˈsteɪdiəm/"],
  ["stand", "khán đài", "/stænd/"],
  ["pitch", "(thể thao) sân", "/pɪtʃ/"],
  ["touchline", "đường biên dọc", "/ˈtʌtʃlaɪn/"],
  ["penalty area", "vòng cấm địa", "/ˈpenəlti eriə/"],
  ["goal", "khung thành", "/ɡəʊl/"],
  ["penalty", "(bóng đá) phạt đền", "/ˈpenəlti/"],
  ["corner kick", "(bóng đá) cú đá phạt góc", "/ˈkɔːrnər kɪk/"],
  ["free kick", "đá phạt trực tiếp", "/ˌfriː ˈkɪk/"],
  ["indirect free kick", "đá phạt gián tiếp", "None"],
  ["kick off", "(trận đấu) bắt đầu, lăn bóng", "None"],
  ["throw-in", "quả ném biên", "None"],
  ["offside", "việt vị", "/ˌɔːfˈsaɪd/"],
  ["corner Flag", "cờ cắm ở góc sân bóng đá", "None"],
  ["bet", "cá độ, đánh cược", "/bet/"],
  ["the bench", "băng ghế dự bị", "None"],
  ["foul", "(thể thao) lỗi, pha phạm lỗi", "/faʊl/"],
  ["goal line", "vạch kẻ (khung thành)", "/ˈɡəʊl laɪn/"],
  ["shoot", "(thể thao) ném, sút, đánh", "/ʃuːt/"],
  ["goalkeeper", "thủ môn", "/ˈɡəʊlkiːpər/"],
  ["defender", "hậu vệ, hàng phòng ngự", "/dɪˈfendər/"],
  ["centre back", "trung vệ", "/ˌsentər ˈbæk/"],
  ["midfielder", "(bóng đá) trung vệ", "/ˌmɪdˈfiːldər/"],
  ["attacking midfielder", "tiền vệ tấn công", "None"],
  ["winger", "tiền vệ cánh nói chung", "/ˈwɪŋər/"],
  ["referee", "trọng tài", "/ˌrefəˈriː/"],
  ["commentator", "bình luận viên", "/ˈkɑːmənteɪtər/"],
  ["supporter", "cổ động viên, người hâm mộ", "/səˈpɔːrtər/"],
  ["linesman", "trọng tài biên", "/ˈlaɪnzmən/"],
  ["hooligan", "kẻ côn đồ, quá khích", "/ˈhuːlɪɡən/"],
  ["red card", "thẻ đỏ", "/ˌred ˈkɑːrd/"],
  ["yellow card", "thẻ vàng", "/ˌjeləʊ ˈkɑːrd/"],
  ["coach", "huấn luyện viên", "/kəʊtʃ/"],
  ["transfer", "cầu thủ chuyển nhượng", "/trænsˈfɜːr/"],
  ["reserve team", "đội dự bị", "None"],
  ["caution", "(bóng đá) cảnh cáo", "/ˈkɔːʃn/"],
  ["stimulant", "chất kích thích", "/ˈstɪmjələnt/"],
  ["strategy", "chiến lược", "/ˈstrætədʒi/"],
  ["striker", "(bóng đá) tiền đạo", "/ˈstraɪkər/"],
  ["winter", "mùa đông", "/ˈwɪntər/"],
  ["candle", "đèn cầy, ngọn nến", "/ˈkændl/"],
  ["snow", "tuyết", "/snəʊ/"],
  ["sack", "bao, túi", "/sæk/"],
  ["card", "thiệp, tấm thiệp", "/kɑːrd/"],
  ["fireplace", "lò sưởi", "/ˈfaɪərpleɪs/"],
  ["chimney", "ống khói", "/ˈtʃɪmni/"],
  ["gift", "quà, quà tặng", "/ɡɪft/"],
  ["Christmas", "lễ Giáng Sinh", "None"],
  ["ornament", "đồ trang trí", "/ˈɔːrnəmənt/"],
  ["pine tree", "(cây) thông", "None"],
  ["sled", "xe trượt tuyết", "/sled/"],
  ["bell", "chuông", "/bel/"],
  ["snowflake", "bông tuyết", "/ˈsnəʊfleɪk/"],
  ["wreath", "vòng hoa", "/riːθ/"],
  ["scarf", "khăn choàng cổ", "/skɑːrf/"],
  ["Christmas tree", "cây thông Giáng Sinh", "None"],
  ["Christmas card", "thiệp Giáng sinh", "None"],
  ["beef", "thịt bò", "/biːf/"],
  ["pork", "thịt heo, thịt lợn", "/pɔːrk/"],
  ["bacon", "(thịt) ba rọi xông khói, ba rọi muối", "/ˈbeɪkən/"],
  ["ham", "thịt đùi, thịt xông khói", "/hæm/"],
  ["yoghurt", "sữa chua", "None"],
  ["pie", "bánh nướng", "/paɪ/"],
  ["bread", "bánh mì", "/bred/"],
  ["cake", "bánh ngọt, bánh nướng", "/keɪk/"],
  ["chip", "khoai tây chiên (lát)", "/tʃɪp/"],
  ["biscuit", "bánh quy", "/ˈbɪskɪt/"],
  ["noodle", "mì, bún", "/ˈnuːdl/"],
  ["butter", "bơ (sữa)", "/ˈbʌtər/"],
  ["olive", "quả ô liu", "/ˈɑːlɪv/"],
  ["soy", "(cây) đậu nành", "None"],
  ["flour", "bột, bột mì", "/ˈflaʊər/"],
  ["lunch", "bữa ăn trưa", "/lʌntʃ/"],
  ["mint", "bạc hà, húng lủi", "/mɪnt/"],
  ["vanilla", "vani", "/vəˈnɪlə/"],
  ["candy", "kẹo", "/ˈkændi/"],
  ["popcorn", "bắp rang, bỏng ngô", "/ˈpɑːpkɔːrn/"],
  ["snack", "bữa ăn nhẹ", "/snæk/"],
  ["barbecue", "tiệc nướng ngoài trời", "/ˈbɑːrbɪkjuː/"],
  ["midday", "trưa, buổi trưa", "/ˌmɪdˈdeɪ/"],
  ["fast food", "thức ăn nhanh", "/ˌfæst ˈfuːd/"],
  ["junk food", "đồ ăn vặt", "/ˈdʒʌŋk fuːd/"],
  ["frozen food", "thực phẩm đông lạnh", "None"],
  ["health food", "thực phẩm tự nhiên", "/ˈhelθ fuːd/"],
  ["distinctive", "đặc trưng, khác biệt", "/dɪˈstɪŋktɪv/"],
  ["flavor", "hương vị", "None"],
  ["balanced diet", "chế độ ăn uống cân bằng", "None"],
  ["stale", "ôi, thiu", "/steɪl/"],
  ["sour", "(vị) chua", "/ˈsaʊər/"],
  ["burnt", "cháy, khét", "/bɜːrnt/"],
  ["overdone", "quá chín, quá rục", "None"],
  ["underdone", "chưa chín, tái", "/ˌʌndərˈdʌn/"],
  ["full", "no", "/fʊl/"],
  ["color", "phẩm màu, chất tạo màu", "/ˈkʌlər/"],
  ["veal", "thịt bê", "/viːl/"],
  ["cereal", "ngũ cốc", "/ˈsɪriəl/"],
  ["hot dog", "bánh mì kẹp xúc xích", "/ˈhɑːt dɔːɡ/"],
  ["sport", "môn thể thao", "/spɔːrt/"],
  ["skiing", "(môn) trượt tuyết", "/ˈskiːɪŋ/"],
  ["ice skating", "(môn) trượt băng", "/ˈaɪs skeɪtɪŋ/"],
  ["horse racing", "môn đua ngựa", "/ˈhɔːrs reɪsɪŋ/"],
  ["running", "(môn) chạy đua", "/ˈrʌnɪŋ/"],
  ["walking", "(môn) đi bộ, tản bộ", "/ˈwɔːkɪŋ/"],
  ["water sports", "thể thao dưới nước", "/ˈwɔːtər spɔːrts/"],
  ["boxing", "(môn) quyền anh, đấm bốc", "/ˈbɑːksɪŋ/"],
  ["swimming", "môn bơi lội", "/ˈswɪmɪŋ/"],
  ["football", "bóng đá", "/ˈfʊtbɔːl/"],
  ["basketball", "(môn) bóng rổ", "/ˈbæskɪtbɔːl/"],
  ["badminton", "(môn) cầu lông", "/ˈbædmɪntən/"],
  ["tennis", "(môn) quần vợt", "/ˈtenɪs/"],
  ["table tennis", "(môn) bóng bàn", "/ˈteɪbl tenɪs/"],
  ["baseball", "(môn) bóng chày", "/ˈbeɪsbɔːl/"],
  ["cycling", "(môn) đua xe đạp, đạp xe", "/ˈsaɪklɪŋ/"],
  ["golf", "(môn) đánh gôn", "/ɡɑːlf/"],
  ["contact sport", "(môn) thể thao tiếp xúc", "/ˈkɑːntækt spɔːrt/"],
  ["water polo", "(môn) bóng nước", "/ˈwɔːtər pəʊləʊ/"],
  ["archery", "bắn cung", "/ˈɑːrtʃəri/"],
  ["frisbee", "(môn) ném đĩa", "None"],
  ["weightlifting", "cử tạ", "/ˈweɪtlɪftɪŋ/"],
  ["wrestling", "(môn) đấu vật", "/ˈreslɪŋ/"],
  ["bowling", "(môn) bóng gỗ, ném banh lăn", "/ˈbəʊlɪŋ/"],
  ["lacrosse", "(môn) bóng vợt", "/ləˈkrɔːs/"],
  ["hockey", "(môn) khúc côn cầu", "/ˈhɑːki/"],
  ["referee", "trọng tài", "/ˌrefəˈriː/"],
  ["dart", "(môn) ném phi tiêu", "/dɑːrt/"],
  ["synchronized swimming", "(môn) bơi nghệ thuật", "/ˌsɪŋkrənaɪzd ˈswɪmɪŋ/"],
  ["SEA Games", "Đại hội Thể thao Đông Nam Á", "None"],
  ["host", "đăng cai, tổ chức", "/həʊst/"],
  ["wushu", "(môn) võ wushu", "None"],
  [
    "sportsmanship",
    "tinh thần thể thao, tinh thần thượng võ",
    "/ˈspɔːrtsmənʃɪp/",
  ],
  ["captain", "đội trưởng", "/ˈkæptɪn/"],
  ["cross-country", "(môn) chạy băng đồng", "/ˌkrɔːs ˈkʌntri/"],
  ["racquetball", "(môn) bóng quần, quần vợt trong nhà", "/ˈrækɪtbɔːl/"],
  ["music", "âm nhạc", "/ˈmjuːzɪk/"],
  ["band", "nhóm nhạc, ban nhạc", "/bænd/"],
  ["play", "(nhạc cụ) biết chơi", "/pleɪ/"],
  ["note", "nốt nhạc", "/nəʊt/"],
  ["drum", "(nhạc cụ) trống", "/drʌm/"],
  ["playlist", "danh sách bài hát", "/ˈpleɪlɪst/"],
  ["musician", "nhạc sĩ", "/mjuˈzɪʃn/"],
  ["perform", "trình diễn, biểu diễn", "/pərˈfɔːrm/"],
  ["rhythm", "nhịp điệu, tiết tấu", "/ˈrɪðəm/"],
  ["dance", "nhảy, biểu diễn", "/dæns/"],
  ["listen", "lắng nghe", "/ˈlɪsn/"],
  ["volume", "âm lượng", "/ˈvɑːljəm/"],
  ["song", "bài hát, bản nhạc", "/sɔːŋ/"],
  ["sing", "hát, ca hát", "/sɪŋ/"],
  ["piano", "dương cầm, đàn piano", "/piˈænəʊ/"],
  ["guitar", "đàn ghi-ta", "/ɡɪˈtɑːr/"],
  ["instrument", "nhạc cụ", "/ˈɪnstrəmənt/"],
  ["harmony", "(âm nhạc) hoà âm", "/ˈhɑːrməni/"],
  ["melody", "giai điệu", "/ˈmelədi/"],
  ["string", "(nhạc cụ) dây đàn", "/strɪŋ/"],
  ["brass", "(nhóm) nhạc cụ bằng đồng", "/bræs/"],
  ["symphony", "bản giao hưởng", "/ˈsɪmfəni/"],
  ["overture", "khúc dạo đầu", "/ˈəʊvərtʃər/"],
  ["conductor", "nhạc trưởng", "/kənˈdʌktər/"],
  ["composer", "nhà soạn nhạc", "/kəmˈpəʊzər/"],
  ["voice", "giọng nói, giọng hát", "/vɔɪs/"],
  ["solo", "độc tấu", "/ˈsəʊləʊ/"],
  ["lead singer", "(ban nhạc) ca sĩ hát chính", "None"],
  ["guitarist", "nghệ sĩ ghi-ta", "/ɡɪˈtɑːrɪst/"],
  ["drummer", "tay trống, người đánh trống", "/ˈdrʌmər/"],
  ["lyric", "lời bài hát", "/ˈlɪrɪk/"],
  ["chorus", "điệp khúc", "/ˈkɔːrəs/"],
  ["opera", "nhạc kịch, ô-pê-ra", "/ˈɑːprə/"],
  ["folk music", "nhạc dân gian", "/ˈfəʊk mjuːzɪk/"],
  ["album", "an-bum, tuyển tập ca khúc", "/ˈælbəm/"],
  ["single", "đĩa đơn", "/ˈsɪŋɡl/"],
  ["tune", "giai điệu", "/tuːn/"],
  ["violin", "đàn vi-ô-lông, vĩ cầm", "/ˌvaɪəˈlɪn/"],
  ["classical music", "nhạc cổ điển", "/ˌklæsɪkl ˈmjuːzɪk/"],
  ["date", "buổi hẹn hò", "/deɪt/"],
  ["engagement", "đính hôn", "/ɪnˈɡeɪdʒmənt/"],
  ["ring", "nhẫn", "None"],
  ["romantic", "(thuộc) tình cảm, lãng mạn", "/rəʊˈmæntɪk/"],
  ["sweet", "tốt bụng, ngọt ngào", "/swiːt/"],
  ["alone", "một mình", "/əˈləʊn/"],
  ["couple", "cặp đôi, đôi vợ chồng", "/ˈkʌpl/"],
  ["forever", "mãi mãi, suốt đời", "/fərˈevər/"],
  ["boyfriend", "bạn trai, người yêu", "/ˈbɔɪfrend/"],
  ["girlfriend", "bạn gái, người yêu", "/ˈɡɜːrlfrend/"],
  ["kiss", "hôn", "/kɪs/"],
  ["heart", "(tình cảm) trái tim", "/hɑːrt/"],
  ["hug", "ôm", "/hʌɡ/"],
  ["propose", "cầu hôn, hỏi cưới", "/prəˈpəʊz/"],
  ["chocolate", "sô-cô-la", "/ˈtʃɔːklət/"],
  ["wedding", "lễ cưới, đám cưới", "/ˈwedɪŋ/"],
  ["anniversary", "ngày kỷ niệm", "/ˌænɪˈvɜːrsəri/"],
  ["darling", "em yêu, anh yêu", "/ˈdɑːrlɪŋ/"],
  ["single", "độc thân", "/ˈsɪŋɡl/"],
  ["restaurant", "nhà hàng", "/ˈrestrɑːnt/"],
  ["main course", "món chính", "/ˌmeɪn ˈkɔːrs/"],
  ["napkin", "khăn ăn", "/ˈnæpkɪn/"],
  ["wine", "rượu vang", "/waɪn/"],
  ["cutlery", "dụng cụ ăn (dao, muỗng, nĩa)", "/ˈkʌtləri/"],
  ["drink", "đồ uống, thức uống", "/drɪŋk/"],
  ["combo", "(sản phẩm) gói, bộ", "/ˈkɑːmbəʊ/"],
  ["side dish", "món phụ, đồ ăn kèm", "/ˈsaɪd dɪʃ/"],
  ["meal", "bữa ăn", "/miːl/"],
  ["order", "gọi món", "/ˈɔːrdər/"],
  ["speciality", "đặc sản", "/ˌspeʃiˈæləti/"],
  ["dessert", "món tráng miệng", "/dɪˈzɜːrt/"],
  ["salad", "(món) rau trộn", "/ˈsæləd/"],
  ["menu", "thực đơn", "/ˈmenjuː/"],
  ["waiter", "bồi bàn, nam phục vụ", "/ˈweɪtər/"],
  ["guest", "(nhà hàng) khách, thực khách", "/ɡest/"],
  ["coupon", "phiếu giảm giá, phiếu đổi quà", "/ˈkuːpɑːn/"],
  ["neat", "gọn gàng, ngăn nắp", "/niːt/"],
  ["animated", "náo nhiệt, sôi nổi", "/ˈænɪmeɪtɪd/"],
  ["hotel", "khách sạn", "/həʊˈtel/"],
  ["hotel receptionist", "nhân viên lễ tân khách sạn", "None"],
  ["housekeeper", "nhân viên dọn phòng", "/ˈhaʊskiːpər/"],
  ["hall", "hành lang", "/hɔːl/"],
  ["vacancy", "(khách sạn) phòng trống", "/ˈveɪkənsi/"],
  ["lobby", "tiền sảnh", "/ˈlɑːbi/"],
  ["concierge", "(khách sạn) nhân viên hướng dẫn", "/kəʊnˈsjerʒ/"],
  ["check in", "(khách sạn) nhận phòng; (sân bay) làm thủ tục đến", "None"],
  ["desk clerk", "(khách sạn) lễ tân", "/ˈdesk klɜːrk/"],
  ["key card", "khóa từ, thẻ từ", "/ˈkiː kɑːrd/"],
  ["double bed", "giường đôi", "None"],
  ["single bed", "giường đơn", "/ˈsɪŋɡl bed/"],
  ["doorman", "nhân viên gác cửa", "/ˈdɔːrmən/"],
  ["reception", "quầy lễ tân", "/rɪˈsepʃn/"],
  ["elevator", "thang máy", "/ˈelɪveɪtər/"],
  ["reservation", "sự đặt chỗ trước", "/ˌrezərˈveɪʃn/"],
  ["bellboy", "(khách sạn) nhân viên hành lý", "/ˈbelbɔɪ/"],
  ["check out", "(khách sạn) trả phòng", "None"],
  ["nursery school", "(trường) mẫu giáo", "/ˈnɜːrsəri skuːl/"],
  ["teacher", "giáo viên", "/ˈtiːtʃər/"],
  ["classmate", "bạn cùng lớp, bạn học", "/ˈklæsmeɪt/"],
  ["library", "thư viện", "/ˈlaɪbreri/"],
  ["pen", "bút mực", "/pen/"],
  ["pencil", "bút chì", "/ˈpensl/"],
  ["ruler", "cây thước", "/ˈruːlər/"],
  ["calculator", "máy tính (toán)", "/ˈkælkjuleɪtər/"],
  ["chalk", "phấn, viên phấn", "/tʃɔːk/"],
  ["student", "sinh viên", "/ˈstuːdnt/"],
  ["classroom", "phòng học, lớp học", "/ˈklæsruːm/"],
  ["elementary school", "(trường) tiểu học", "/ˌelɪˈmentri skuːl/"],
  ["high school", "trung học phổ thông", "/ˈhaɪ skuːl/"],
  ["trade school", "trường dạy nghề", "/ˈtreɪd skuːl/"],
  ["college", "(trường) đại học, cao đẳng", "/ˈkɑːlɪdʒ/"],
  ["university", "(trường) đại học", "/ˌjuːnɪˈvɜːrsəti/"],
  ["principal", "hiệu trưởng", "/ˈprɪnsəpl/"],
  ["blackboard", "bảng đen", "/ˈblækbɔːrd/"],
  ["compass", "com-pa", "/ˈkʌmpəs/"],
  ["middle school", "(trường) trung học cơ sở", "/ˈmɪdl skuːl/"],
  ["history", "(ngành/môn) lịch sử", "/ˈhɪstri/"],
  ["economics", "(ngành/môn) kinh tế học", "/ˌiːkəˈnɑːmɪks/"],
  ["chemistry", "(ngành/môn) hóa học", "/ˈkemɪstri/"],
  ["biology", "(ngành/môn) sinh học", "/baɪˈɑːlədʒi/"],
  ["IT", "(ngành/môn) công nghệ thông tin", "None"],
  ["geography", "(ngành/môn) địa lý", "/dʒiˈɑːɡrəfi/"],
  ["arts", "(môn) mỹ thuật", "None"],
  ["fail", "(thi cử) rớt; đánh rớt", "/feɪl/"],
  ["graduate", "tốt nghiệp, ra trường", "/ˈɡrædʒuət/"],
  ["degree", "học vị, bằng cấp", "/dɪˈɡriː/"],
  ["playground", "sân chơi", "/ˈpleɪɡraʊnd/"],
  ["uniform", "đồng phục", "/ˈjuːnɪfɔːrm/"],
  ["grade", "điểm số", "/ɡreɪd/"],
  ["homeroom teacher", "giáo viên chủ nhiệm", "None"],
  ["proctor", "giám thị, người gác thi", "/ˈprɑːktər/"],
  ["school bag", "cặp (đi học)", "None"],
  ["dean", "trưởng khoa, trưởng bộ môn", "/diːn/"],
  ["lesson", "khóa học, lớp", "/ˈlesn/"],
  ["red", "màu đỏ", "/red/"],
  ["cream", "màu kem", "/kriːm/"],
  ["purple", "màu tím", "/ˈpɜːrpl/"],
  ["black", "màu đen", "/blæk/"],
  ["gray", "màu xám", "/ɡreɪ/"],
  ["silver", "màu bạc", "/ˈsɪlvər/"],
  ["gold", "màu vàng kim", "/ɡəʊld/"],
  ["copper", "màu đồng", "/ˈkɑːpər/"],
  ["green", "màu xanh lục", "/ɡriːn/"],
  ["pink", "màu hồng", "/pɪŋk/"],
  ["yellow", "màu vàng", "/ˈjeləʊ/"],
  ["brown", "màu nâu", "/braʊn/"],
  ["blue", "màu xanh lam", "/bluː/"],
  ["chestnut", "(màu) nâu hạt dẻ", "/ˈtʃesnʌt/"],
  ["turquoise", "(màu) xanh ngọc", "/ˈtɜːrkwɔɪz/"],
  ["lime green", "(màu) xanh đọt chuối", "/ˌlaɪm ˈɡriːn/"],
  ["navy blue", "(màu) xanh hải quân", "/ˌneɪvi ˈbluː/"],
  ["bright red", "(màu) đỏ tươi", "None"],
  ["vivid", "(màu sắc) rực rỡ, sáng", "/ˈvɪvɪd/"],
  ["white", "màu trắng", "/waɪt/"],
  ["weather", "thời tiết", "/ˈweðər/"],
  ["warm", "ấm áp, ấm", "/wɔːrm/"],
  ["wind", "gió", "None"],
  ["rain", "mưa", "/reɪn/"],
  ["temperature", "nhiệt độ", "/ˈtemprətʃər/"],
  ["weather forecast", "(bản tin) dự báo thời tiết", "/ˈweðər fɔːrkæst/"],
  ["sunny", "có nắng", "/ˈsʌni/"],
  ["sunshine", "ánh nắng, ánh mặt trời", "/ˈsʌnʃaɪn/"],
  ["icy", "lạnh cóng", "/ˈaɪsi/"],
  ["atmosphere", "bầu khí quyển", "/ˈætməsfɪr/"],
  ["dry", "(thời tiết) khô, hạn", "/draɪ/"],
  ["sun", "mặt trời", "/sʌn/"],
  ["cloud", "mây, đám mây", "/klaʊd/"],
  ["fog", "sương mù", "/fɑːɡ/"],
  ["snow", "tuyết", "/snəʊ/"],
  ["cold", "lạnh, lạnh lẽo", "/kəʊld/"],
  ["cool", "mát mẻ", "/kuːl/"],
  ["hot", "nóng", "/hɑːt/"],
  ["wet", "có mưa", "/wet/"],
  ["erratic", "thất thường, bất ngờ", "/ɪˈrætɪk/"],
  ["thunder", "sấm, tiếng sấm", "/ˈθʌndər/"],
  ["hailstone", "viên mưa đá", "/ˈheɪlstəʊn/"],
  ["blustery", "có gió lớn", "/ˈblʌstəri/"],
  ["downpour", "mưa rào, mưa lớn", "/ˈdaʊnpɔːr/"],
  ["raincoat", "áo mưa", "/ˈreɪnkəʊt/"],
  ["blizzard", "bão tuyết", "/ˈblɪzərd/"],
  ["rainbow", "cầu vồng ", "/ˈreɪnbəʊ/"],
  ["dew", "sương", "/duː/"],
  ["sleet", "mưa tuyết", "/sliːt/"],
  ["stormy", "có giông, có bão", "/ˈstɔːrmi/"],
  ["snowflake", "bông tuyết", "/ˈsnəʊfleɪk/"],
  ["puddle", "vũng nước", "/ˈpʌdl/"],
  ["lightning", "chớp, sấm chớp", "/ˈlaɪtnɪŋ/"],
  ["mild", "se lạnh, mát mẻ", "/maɪld/"],
  ["dull", "u ám, nhiều mây", "/dʌl/"],
  ["shelter", "trú ẩn, ẩn náu", "/ˈʃeltər/"],
  ["run away", "chạy trốn, bỏ chạy", "None"],
  ["Celsius", "(thuộc) độ C", "None"],
  ["fine", "(thời tiết) đẹp, quang đãng", "/faɪn/"],
  ["skirt", "váy", "/skɜːrt/"],
  ["leggings", "quần ôm, quần bó", "/ˈleɡɪŋz/"],
  ["overall", "quần yếm", "/ˌəʊvərˈɔːl/"],
  ["turtleneck", "áo len cổ lọ", "/ˈtɜːrtlnek/"],
  ["bow tie", "nơ bướm", "/ˌbəʊ ˈtaɪ/"],
  ["tie", "cà vạt", "/taɪ/"],
  ["tunic", "áo trùm hông", "/ˈtuːnɪk/"],
  ["vest", "áo gi-lê", "/vest/"],
  ["T-shirt", "áo phông, áo thun tay ngắn", "None"],
  ["shirt", "áo sơ mi", "/ʃɜːrt/"],
  ["jeans", "quần jean", "/dʒiːnz/"],
  ["dress", "áo đầm, váy", "/dres/"],
  ["coat", "áo choàng, áo khoác", "/kəʊt/"],
  ["jacket", "áo khoác", "/ˈdʒækɪt/"],
  ["sweater", "áo len", "/ˈswetər/"],
  ["jumpsuit", "đồ bay, bộ áo liền quần", "/ˈdʒʌmpsuːt/"],
  ["shorts", "quần đùi, quần soóc", "/ʃɔːrts/"],
  ["suit", "bộ com lê, bộ âu phục", "/suːt/"],
  ["anorak", "áo choàng có mũ trùm đầu", "/ˈænəræk/"],
  ["hat", "mũ, nón", "/hæt/"],
  ["cap", "mũ lưỡi trai", "/kæp/"],
  ["glove", "găng tay", "/ɡlʌv/"],
  ["scarf", "khăn choàng cổ", "/skɑːrf/"],
  ["sandal", "dép quai hậu, giầy xăng-đan", "/ˈsændl/"],
  ["slipper", "dép lê (đi trong nhà)", "/ˈslɪpər/"],
  ["pocket", "(quần áo) túi", "/ˈpɑːkɪt/"],
  ["sleeve", "tay áo", "/sliːv/"],
  ["collar", "cổ áo", "/ˈkɑːlər/"],
  ["zip", "khóa kéo", "/zɪp/"],
  ["blouse", "áo nữ", "/blaʊs/"],
  ["button", "khuy, nút", "/ˈbʌtn/"],
  ["underwear", "đồ lót", "/ˈʌndərwer/"],
  ["bra", "áo ngực", "/brɑː/"],
  ["pant", "quần dài", "/pænt/"],
  ["belt", "dây nịt, thắt lưng", "/belt/"],
  ["high heels", "giày cao gót", "/ˌhaɪ ˈhiːlz/"],
  ["try on", "thử (quần áo) ", "None"],
  ["size", "(quần áo) cỡ, khổ, số", "/saɪz/"],
  ["head", "cái đầu", "/hed/"],
  ["face", "khuôn mặt", "/feɪs/"],
  ["hair", "tóc", "/her/"],
  ["ear", "tai, lỗ tai", "/ɪr/"],
  ["neck", "cổ, cần cổ", "/nek/"],
  ["forehead", "trán", "/ˈfɔːrhed/"],
  ["beard", "râu, bộ râu", "/bɪrd/"],
  ["eye", "mắt, con mắt", "/aɪ/"],
  ["nose", "mũi, lỗ mũi", "/nəʊz/"],
  ["mouth", "miệng", "/maʊθ/"],
  ["chin", "cằm", "/tʃɪn/"],
  ["shoulder", "vai, bờ vai", "/ˈʃəʊldər/"],
  ["elbow", "khuỷu tay", "/ˈelbəʊ/"],
  ["arm", "cánh tay", "/ɑːrm/"],
  ["chest", "ngực", "/tʃest/"],
  ["armpit", "nách", "/ˈɑːrmpɪt/"],
  ["wrist", "cổ tay", "/rɪst/"],
  ["navel", "rún, rốn", "/ˈneɪvl/"],
  ["ankle", "mắt cá chân", "/ˈæŋkl/"],
  ["waist", "eo", "/weɪst/"],
  ["abdomen", "vùng bụng", "/ˈæbdəmən/"],
  ["leg", "chân", "/leɡ/"],
  ["thigh", "đùi, bắp đùi", "/θaɪ/"],
  ["knee", "đầu gối", "/niː/"],
  ["hand", "bàn tay", "/hænd/"],
  ["thumb", "ngón tay cái", "/θʌm/"],
  ["boarding school", "trường nội trú", "/ˈbɔːrdɪŋ skuːl/"],
  ["state school", "trường nhà nước, trường công lập", "/ˈsteɪt skuːl/"],
  ["secondary school", "trường cấp hai, trung học cơ sở", "/ˈsekənderi skuːl/"],
  ["primary", "(giáo dục) tiểu học, cấp một", "/ˈpraɪmeri/"],
  ["nursery school", "(trường) mẫu giáo", "/ˈnɜːrsəri skuːl/"],
  ["school", "ngôi trường, trường học", "/skuːl/"],
  ["college", "(trường) đại học, cao đẳng", "/ˈkɑːlɪdʒ/"],
  ["university", "(trường) đại học", "/ˌjuːnɪˈvɜːrsəti/"],
  ["professor", "giáo sư", "/prəˈfesər/"],
  ["lecturer", "giảng viên (đại học)", "/ˈlektʃərər/"],
  ["researcher", "nghiên cứu viên, nhà nghiên cứu", "/ˈriːsɜːrtʃər/"],
  ["graduate", "sinh viên tốt nghiệp, cử nhân", "/ˈɡrædʒuət/"],
  ["degree", "học vị, bằng cấp", "/dɪˈɡriː/"],
  ["thesis", "luận văn, luận án", "/ˈθiːsɪs/"],
  ["lecture", "bài giảng", "/ˈlektʃər/"],
  ["debate", "cuộc thảo luận, tranh luận", "/dɪˈbeɪt/"],
  ["higher education", "(giáo dục) đại học", "/ˌhaɪər edʒuˈkeɪʃn/"],
  ["semester", "học kỳ", "/sɪˈmestər/"],
  ["student", "sinh viên", "/ˈstuːdnt/"],
  ["student union", "hội sinh viên", "None"],
  ["tuition", "học phí, tiền học", "/tuˈɪʃn/"],
  ["exam", "bài thi, kì thi", "/ɪɡˈzæm/"],
  ["fail", "sự thi trượt, điểm hỏng", "/feɪl/"],
  ["pass", "đậu, đỗ", "/pæs/"],
  ["study", "học", "/ˈstʌdi/"],
  ["learn", "học", "/lɜːrn/"],
  ["curriculum", "chương trình giảng dạy", "/kəˈrɪkjələm/"],
  ["course", "khóa học", "/kɔːrs/"],
  ["subject", "môn học", "/ˈsʌbdʒɪkt/"],
  ["grade", "điểm số", "/ɡreɪd/"],
  ["mark", "điểm, điểm số", "/mɑːrk/"],
  ["qualification", "năng lực, chuyên môn", "/ˌkwɑːlɪfɪˈkeɪʃn/"],
  ["certificate", "chứng chỉ, bằng", "/sərˈtɪfɪkət/"],
  ["attendance", "sự có mặt", "/əˈtendəns/"],
  ["projector", "máy chiếu", "/prəˈdʒektər/"],
  ["textbook", "sách giáo khoa", "/ˈtekstbʊk/"],
  ["question", "câu hỏi", "/ˈkwestʃən/"],
  ["answer", "trả lời, đáp lại", "/ˈænsər/"],
  ["mistake", "sai lầm, nhầm lẫn", "/mɪˈsteɪk/"],
  ["right", "đúng, chính xác", "/raɪt/"],
  ["wrong", "sai, nhầm lẫn", "/rɔːŋ/"],
  ["register", "sổ, sổ sách", "/ˈredʒɪstər/"],
  ["assembly", "(sự) hội họp, tập trung", "/əˈsembli/"],
  ["holiday", "kỳ nghỉ", "/ˈhɑːlədeɪ/"],
  ["teacher", "giáo viên", "/ˈtiːtʃər/"],
  ["pupil", "học trò, học sinh", "/ˈpjuːpl/"],
  ["playground", "sân chơi", "/ˈpleɪɡraʊnd/"],
  ["library", "thư viện", "/ˈlaɪbreri/"],
  ["hall", "hội trường", "/hɔːl/"],
  ["hall of residence", "ký túc xá", "/ˌhɔːl əv ˈrezɪdəns/"],
  ["locker", "tủ có khoá, két có khoá", "/ˈlɑːkər/"],
  ["classroom", "phòng học, lớp học", "/ˈklæsruːm/"],
  ["chalk", "phấn, viên phấn", "/tʃɔːk/"],
  ["lesson", "khóa học, lớp", "/ˈlesn/"],
  ["homework", "bài tập về nhà", "/ˈhəʊmwɜːrk/"],
  ["test", "kiểm tra", "/test/"],
  ["husband", "chồng", "/ˈhʌzbənd/"],
  ["grandson", "cháu trai (của ông bà)", "/ˈɡrænsʌn/"],
  ["uncle", "chú, bác, cậu, dượng", "/ˈʌŋkl/"],
  ["aunt", "cô, dì, thím, mợ, bác gái", "/ænt/"],
  ["niece", "cháu gái (của cô, dì, chú, bác)", "/niːs/"],
  ["nephew", "cháu trai (của cô, dì, chú, bác)", "/ˈnefjuː/"],
  ["son-in-law", "con rể", "/ˈsʌn ɪn lɔː/"],
  ["daughter-in-law", "con dâu", "/ˈdɔːtər ɪn lɔː/"],
  ["granddaughter", "cháu gái (của ông bà)", "/ˈɡrændɔːtər/"],
  ["grandfather", "ông nội, ông ngoại", "/ˈɡrænfɑːðər/"],
  ["wife", "vợ", "/waɪf/"],
  ["father", "cha, bố, ba", "/ˈfɑːðər/"],
  ["mother", "mẹ, má", "/ˈmʌðər/"],
  ["daughter", "con gái", "/ˈdɔːtər/"],
  ["son", "con trai", "/sʌn/"],
  ["sister", "chị gái, em gái", "/ˈsɪstər/"],
  ["brother", "anh trai, em trai", "/ˈbrʌðər/"],
  ["grandmother", "bà nội, bà ngoại", "/ˈɡrænmʌðər/"],
  ["brother-in-law", "anh/em rể, anh/em chồng, anh/em vợ", "/ˈbrʌðər ɪn lɔː/"],
  ["cousin", "anh họ, em họ", "/ˈkʌzn/"],
  ["parent", "bố, mẹ", "/ˈperənt/"],
  ["relative", "họ hàng, bà con, người thân", "/ˈrelətɪv/"],
  ["mother-in-law", "mẹ chồng, mẹ vợ", "/ˈmʌðər ɪn lɔː/"],
  ["father-in-law", "bố chồng, bố vợ", "/ˈfɑːðər ɪn lɔː/"],
  ["sister-in-law", "chị/em dâu, chị/em chồng, chị/em vợ", "/ˈsɪstər ɪn lɔː/"],
  ["adopt", "nhận con nuôi", "/əˈdɑːpt/"],
  ["children", "con cái", "None"],
  ["take care of", "chăm sóc, quan tâm", "None"],
  ["family tree", "sơ đồ phả hệ, gia phả", "/ˌfæməli ˈtriː/"],
  ["anniversary", "ngày kỷ niệm", "/ˌænɪˈvɜːrsəri/"],
  ["close-knit", "(quan hệ) khăng khít, gắn bó", "/ˌkləʊs ˈnɪt/"],
  ["stepchild", "con riêng", "/ˈsteptʃaɪld/"],
  [
    "half-brother",
    "anh trai, em trai (cùng cha/mẹ khác mẹ/cha)",
    "/ˈhæf brʌðər/",
  ],
  ["half-sister", "chị gái, em gái (cùng cha/mẹ khác mẹ/cha)", "/ˈhæf sɪstər/"],
  ["godfather", "cha đỡ đầu", "/ˈɡɑːdfɑːðər/"],
  ["hereditary", "(được) kế thừa, di truyền", "/həˈredɪteri/"],
  ["stepmother", "mẹ kế", "/ˈstepmʌðər/"],
  ["stepfather", "cha dượng", "/ˈstepfɑːðər/"],
  ["orphan", "trẻ mồ côi, cô nhi", "/ˈɔːrfn/"],
  ["generation", "(trong gia tộc) đời, thế hệ", "/ˌdʒenəˈreɪʃn/"],
  ["orange", "quả cam", "/ˈɔːrɪndʒ/"],
  ["lemon", "quả chanh vàng", "/ˈlemən/"],
  ["mango", "(quả) xoài", "/ˈmæŋɡəʊ/"],
  ["apple", "quả táo", "/ˈæpl/"],
  ["tangerine", "quả quýt", "/ˈtændʒəriːn/"],
  ["grape", "quả nho", "/ɡreɪp/"],
  ["strawberry", "quả dâu tây", "/ˈstrɔːberi/"],
  ["melon", "quả dưa lưới", "/ˈmelən/"],
  ["passion fruit", "quả chanh dây", "/ˈpæʃn fruːt/"],
  ["grapefruit", "quả bưởi chùm, bưởi bồ đào", "/ˈɡreɪpfruːt/"],
  ["watermelon", "quả dưa hấu", "/ˈwɔːtərmelən/"],
  ["peach", "quả đào", "/piːtʃ/"],
  ["pear", "quả lê", "/per/"],
  ["banana", "quả chuối", "/bəˈnænə/"],
  ["plum", "quả mận", "/plʌm/"],
  ["papaya", "(quả) đu đủ", "/pəˈpaɪə/"],
  ["avocado", "(quả) bơ", "/ˌævəˈkɑːdəʊ/"],
  ["starfruit", "quả khế", "None"],
  ["pineapple", "quả dứa, quả thơm", "/ˈpaɪnæpl/"],
  ["coconut", "quả dừa", "/ˈkəʊkənʌt/"],
  ["raspberry", "quả mâm xôi", "/ˈræzberi/"],
  ["nectarine", "quả xuân đào", "/ˈnektəriːn/"],
  ["mulberry", "quả dâu tằm", "/ˈmʌlberi/"],
  ["raisin", "nho khô", "/ˈreɪzn/"],
  ["jackfruit", "quả mít", "/ˈdʒækfruːt/"],
  ["persimmon", "quả hồng", "/pərˈsɪmən/"],
  ["dragon fruit", "quả thanh long", "/ˈdræɡən fruːt/"],
  ["custard apple", "(quả) na, mãng cầu", "/ˈkʌstərd æpl/"],
  ["quince", "quả mộc qua", "/kwɪns/"],
  ["cherry", "quả anh đào", "/ˈtʃeri/"],
  ["kiwi", "quả kiwi", "/ˈkiːwi/"],
  ["pomegranate", "quả lựu", "/ˈpɑːmɪɡrænɪt/"],
  ["guava", "quả ổi", "/ˈɡwɑːvə/"],
  ["apricot", "quả mơ", "/ˈæprɪkɑːt/"],
  ["blueberry", "quả việt quất", "/ˈbluːberi/"],
  ["durian", "quả sầu riêng", "/ˈdʊriən/"],
  ["lychee", "quả vải", "/ˈliːtʃi/"],
  ["tamarind", "quả me", "/ˈtæmərɪnd/"],
  ["kumquat", "quả quất vàng", "/ˈkʌmkwɑːt/"],
  ["save as", "(tin học) lưu với định dạng", "None"],
  ["select", "(tin học) chọn, nhấn chọn", "/sɪˈlekt/"],
  ["copy", "(tin học) sao chép", "/ˈkɑːpi/"],
  ["paste", "(tin học) dán", "/peɪst/"],
  ["piglet", "lợn con, heo con", "/ˈpɪɡlət/"],
  ["sow", "heo nái, lợn cái", "None"],
  ["pig", "(loài) lợn", "/pɪɡ/"],
  ["duck", "vịt cái", "/dʌk/"],
  ["animal", "động vật", "/ˈænɪml/"],
  ["goat", "(loài) dê", "/ɡəʊt/"],
  ["horse", "(loài) ngựa", "/hɔːrs/"],
  ["goose", "(loài) ngỗng", "/ɡuːs/"],
  ["donkey", "(loài) lừa", "/ˈdɑːŋki/"],
  ["sheep", "(loài) cừu", "/ʃiːp/"],
  ["ox", "bò đực thiến", "/ɑːks/"],
  ["dog", "(loài) chó", "/dɔːɡ/"],
  ["cat", "(loài) mèo", "/kæt/"],
  ["chicken", "thịt gà", "/ˈtʃɪkɪn/"],
  ["rooster", "gà trống", "/ˈruːstər/"],
  ["hen", "gà mái", "/hen/"],
  ["cow", "(loài) bò, bò cái", "/kaʊ/"],
  ["bull", "bò đực", "/bʊl/"],
  ["calf", "bê, bò con", "/kæf/"],
  ["rabbit", "(loài) thỏ", "/ˈræbɪt/"],
  ["owl", "(loài) cú", "/aʊl/"],
  ["deer", "(loài) hươu, nai", "/dɪr/"],
  ["bat", "(loài) dơi", "/bæt/"],
  ["mink", "(loài) chồn nâu", "/mɪŋk/"],
  ["monkey", "(loài) khỉ", "/ˈmʌŋki/"],
  ["snake", "(loài) rắn", "/sneɪk/"],
  ["lizard", "(loài) thằn lằn", "/ˈlɪzərd/"],
  ["giraffe", "(loài) hươu cao cổ", "/dʒəˈræf/"],
  ["bear", "(loài) gấu", "/ber/"],
  ["rhino", "(loài) tê giác", "/ˈraɪnəʊ/"],
  ["elephant", "(loài) voi", "/ˈelɪfənt/"],
  ["panther", "(loài) báo đen", "/ˈpænθər/"],
  ["tiger", "(loài) hổ, cọp", "/ˈtaɪɡər/"],
  ["lion", "(loài) sư tử", "/ˈlaɪən/"],
  ["fox", "(loài) cáo", "/fɑːks/"],
  ["dinosaur", "(loài) khủng long", "/ˈdaɪnəsɔːr/"],
  ["turtle", "(loài) rùa biển", "/ˈtɜːrtl/"],
  ["snail", "(loài) ốc sên", "/sneɪl/"],
  ["crow", "(loài) quạ", "/krəʊ/"],
  ["parrot", "con vẹt", "/ˈpærət/"],
  ["caterpillar", "sâu bướm", "/ˈkætərpɪlər/"],
  ["cocoon", "cái kén (tằm)", "/kəˈkuːn/"],
  ["butterfly", "(loài) bướm", "/ˈbʌtərflaɪ/"],
  ["dragonfly", "(loài) chuồn chuồn", "/ˈdræɡənflaɪ/"],
  ["cricket", "(loài) dế", "/ˈkrɪkɪt/"],
  ["grasshopper", "(loài) châu chấu", "/ˈɡræshɑːpər/"],
  ["cockroach", "(loài) gián", "/ˈkɑːkrəʊtʃ/"],
  ["beetle", "(loài) bọ cánh cứng", "/ˈbiːtl/"],
  ["termite", "(loài) mối, mọt", "/ˈtɜːrmaɪt/"],
  ["ant", "(loài) kiến", "/ænt/"],
  ["mosquito", "(loài) muỗi", "/məˈskiːtəʊ/"],
  ["ladybug", "(loài) bọ rùa", "None"],
  ["spider", "(loài) nhện", "/ˈspaɪdər/"],
  ["firefly", "(loài) đom đóm", "/ˈfaɪərflaɪ/"],
  ["fly", "(loài) ruồi", "/flaɪ/"],
  ["bee", "(loài) ong", "/biː/"],
  ["wasp", "(loài) ong bắp cày", "/wɑːsp/"],
  ["mother", "mẹ, má", "/ˈmʌðər/"],
  ["centipede", "(loài) rết", "/ˈsentɪpiːd/"],
  ["class", "lớp học", "/klæs/"],
  ["classroom", "phòng học, lớp học", "/ˈklæsruːm/"],
  ["textbook", "sách giáo khoa", "/ˈtekstbʊk/"],
  ["exercise book", "sách bài tập", "/ˈeksərsaɪz bʊk/"],
  ["reference book", "sách tham khảo", "/ˈrefrəns bʊk/"],
  ["notebook", "sổ ghi chép", "/ˈnəʊtbʊk/"],
  ["notepad", "sổ tay, sổ ghi chép", "/ˈnəʊtpæd/"],
  ["marker", "dấu hiệu", "/ˈmɑːrkər/"],
  ["pencil", "bút chì", "/ˈpensl/"],
  ["crayon", "bút màu sáp", "/ˈkreɪən/"],
  ["pencil sharpener", "đồ chuốt, đồ gọt bút chì", "/ˈpensl ʃɑːrpnər/"],
  ["eraser", "cục tẩy, cục gôm", "/ɪˈreɪsər/"],
  ["pen", "bút mực", "/pen/"],
  ["ballpoint pen", "bút bi", "None"],
  ["paper", "giấy", "/ˈpeɪpər/"],
  ["desk", "bàn học, bàn làm việc", "/desk/"],
  ["map", "bản đồ", "/mæp/"],
  ["glue", "keo, hồ dán", "/ɡluː/"],
  ["scissors", "cái kéo", "/ˈsɪzərz/"],
  ["ruler", "cây thước", "/ˈruːlər/"],
  ["protractor", "thước đo độ", "/prəˈtræktər/"],
  ["ink", "mực (viết, vẽ)", "/ɪŋk/"],
  ["chalk", "phấn, viên phấn", "/tʃɔːk/"],
  ["folder", "(tin học) thư mục", "/ˈfəʊldər/"],
  ["tree", "cây, cây cối", "/triː/"],
  ["beech", "gỗ dẻ gai", "/biːtʃ/"],
  ["pine", "cây thông", "/paɪn/"],
  ["cedar", "gỗ tuyết tùng", "/ˈsiːdər/"],
  ["oak", "cây sồi", "/əʊk/"],
  ["ivy", "dây thường xuân", "/ˈaɪvi/"],
  ["moss", "rong, rêu", "/mɔːs/"],
  ["mushroom", "nấm", "/ˈmʌʃrʊm/"],
  ["wheat", "(cây) lúa mì", "/wiːt/"],
  ["corn", "bắp, ngô", "/kɔːrn/"],
  ["flower", "hoa, cây hoa", "/ˈflaʊər/"],
  ["grass", "cây cỏ, cỏ", "/ɡræs/"],
  ["herb", "thảo mộc, rau thơm", "/ɜːrb/"],
  ["bush", "bụi cây, bụi rậm", "/bʊʃ/"],
  ["coconut tree", "(cây) dừa", "None"],
  ["apple tree", "cây táo", "None"],
  ["shrubland", "vùng cây bụi", "None"],
  ["Denmark", "(nước) Đan Mạch", "None"],
  ["England", "(nước) Anh", "None"],
  ["Sweden", "(nước) Thụy Điển", "None"],
  ["Austria", "(nước) Áo", "None"],
  ["France", "(nước) Pháp", "None"],
  ["Germany", "(nước) Đức", "None"],
  ["Switzerland", "(nước) Thụy Sĩ", "None"],
  ["Greece", "(thuộc) Hy Lạp", "None"],
  ["Italy", "(nước) Ý", "None"],
  ["Spain", "(nước) Tây Ban Nha", "None"],
  ["Russia", "(nước) Nga", "None"],
  ["Canada", "(nước) Canada", "None"],
  ["Mexico", "(nước) Mêxicô", "None"],
  ["America", "(nước) Mỹ, Hoa Kỳ", "None"],
  ["Brazil", "(nước) Braxin", "None"],
  ["herring", "cá trích", "/ˈherɪŋ/"],
  ["skate", "(loài) cá đuối", "/skeɪt/"],
  ["salmon", "(loài) cá hồi", "/ˈsæmən/"],
  ["prawn", "(loài) tôm", "/prɔːn/"],
  ["cuttlefish", "(loài) mực nang", "/ˈkʌtlfɪʃ/"],
  ["lobster", "(thịt) tôm hùm", "/ˈlɑːbstər/"],
  ["squid", "(loài) mực ống", "/skwɪd/"],
  ["shrimp", "(loài) tôm", "/ʃrɪmp/"],
  ["oyster", "(loài) hàu", "/ˈɔɪstər/"],
  ["crab", "(loài) cua", "/kræb/"],
  ["cockle", "(loài) sò huyết", "/ˈkɑːkl/"],
  ["scallop", "(loài) sò điệp", "/ˈskæləp/"],
  ["octopus", "(loài) bạch tuộc", "/ˈɑːktəpʊs/"],
  ["fish", "(thức ăn) cá", "/fɪʃ/"],
  ["eel", "con lươn; thịt lươn", "/iːl/"],
  ["mussel", "(loài) vẹm, chem chép", "/ˈmʌsl/"],
  ["clam", "(loài) nghêu, ngao", "/klæm/"],
  ["charcoal", "than củi", "/ˈtʃɑːrkəʊl/"],
  ["battery", "pin", "/ˈbætəri/"],
  ["gasoline", "xăng", "/ˈɡæsəliːn/"],
  ["turbine", "tua-bin, động cơ", "/ˈtɜːrbaɪn/"],
  ["sun", "mặt trời", "/sʌn/"],
  ["wind", "gió", "None"],
  ["geyser", "mạch nước phun", "/ˈɡaɪzər/"],
  ["waterfall", "thác nước", "/ˈwɔːtərfɔːl/"],
  ["refinery", "nhà máy lọc", "/rɪˈfaɪnəri/"],
  ["nuclear reactor", "lò phản ứng hạt nhân", "/ˌnuːkliər riˈæktər/"],
  ["dam", "đập (nước/thủy điện)", "/dæm/"],
  ["power plant", "nhà máy điện", "/ˈpaʊər plænt/"],
  ["transformer", "máy biến áp", "/trænsˈfɔːrmər/"],
  ["heat", "sưởi ấm, làm nóng; nóng/ấm lên", "/hiːt/"],
  ["natural gas", "khí tự nhiên", "/ˌnætʃrəl ˈɡæs/"],
  ["diesel", "dầu đi-ê-zen", "/ˈdiːzl/"],
  ["solar power", "năng lượng mặt trời", "/ˌsəʊlər ˈpaʊər/"],
  ["dancer", "vũ công", "/ˈdænsər/"],
  ["designer", "nhà thiết kế", "/dɪˈzaɪnər/"],
  ["magician", "ảo thuật gia", "/məˈdʒɪʃn/"],
  ["teller", "nhân viên ngân hàng", "/ˈtelər/"],
  ["tour guide", "hướng dẫn viên du lịch", "None"],
  ["sailor", "thủy thủ", "/ˈseɪlər/"],
  ["commentator", "bình luận viên", "/ˈkɑːmənteɪtər/"],
  ["dentist", "nha sĩ", "/ˈdentɪst/"],
  ["postman", "người đưa thư", "/ˈpəʊstmən/"],
  ["writer", "nhà văn, tác giả, biên kịch", "/ˈraɪtər/"],
  ["pilot", "phi công", "/ˈpaɪlət/"],
  ["plumber", "thợ sửa ống nước", "/ˈplʌmər/"],
  ["tailor", "thợ may", "/ˈteɪlər/"],
  ["copywriter", "người viết bài, biên tập viên (quảng cáo)", "/ˈkɑːpiraɪtər/"],
  ["journalist", "nhà báo", "/ˈdʒɜːrnəlɪst/"],
  ["grocer", "người bán tạp hóa", "/ˈɡrəʊsər/"],
  ["clerk", "viên thư ký, nhân viên trực", "/klɜːrk/"],
  ["assistant", "trợ lý", "/əˈsɪstənt/"],
  ["model", "người mẫu thời trang", "/ˈmɑːdl/"],
  ["freelance", "người làm việc tự do, người lao động độc lập", "/ˈfriːlæns/"],
  ["consultant", "cố vấn, chuyên viên tư vấn", "/kənˈsʌltənt/"],
  ["self-employed", "tự làm chủ, làm việc tự do", "/ˌself ɪmˈplɔɪd/"],
  ["supervisor", "người giám sát", "/ˈsuːpərvaɪzər/"],
  ["sales manager", "trưởng phòng kinh doanh, giám đốc kinh doanh", "None"],
  ["production manager", "trưởng phòng sản xuất", "None"],
  ["mechanic", "thợ cơ khí", "/məˈkænɪk/"],
  ["managing director", "giám đốc điều hành", "/ˌmænɪdʒɪŋ dəˈrektər/"],
  [
    "personal assistant",
    "trợ lý cá nhân, trợ lý riêng",
    "/ˌpɜːrsənl əˈsɪstənt/",
  ],
  ["hairdresser", "thợ cắt tóc, thợ làm tóc", "/ˈherdresər/"],
  ["architect", "kiến trúc sư", "/ˈɑːrkɪtekt/"],
  ["marketing executive", "nhân viên truyền thông", "None"],
  ["engineer", "kỹ sư", "/ˌendʒɪˈnɪr/"],
  ["vet", "bác sĩ thú y", "/vet/"],
  ["shoemaker", "thợ đóng giày", "/ˈʃuːmeɪkər/"],
  ["translator", "biên dịch viên, dịch giả", "/trænzˈleɪtər/"],
  ["interpreter", "phiên dịch viên, thông dịch viên", "/ɪnˈtɜːrprətər/"],
  ["sanitation worker", "lao công, nhân viên vệ sinh", "/ˌsænɪˈteɪʃn wɜːrkər/"],
  ["business manager", "giám đốc kinh doanh", "None"],
  ["police officer", "viên cảnh sát", "/pəˈliːs ɑːfɪsər/"],
  ["personnel manager", "trưởng phòng nhân sự, giám đốc nhân sự", "None"],
  ["keep-fit", "(bài tập) thể dục", "/ˌkiːp ˈfɪt/"],
  ["regular", "(xảy ra) thường xuyên", "/ˈreɡjələr/"],
  ["diabetes", "(bệnh) tiểu đường", "/ˌdaɪəˈbiːtiːz/"],
  ["dietitian", "chuyên gia dinh dưỡng", "None"],
  ["goiter", "(bệnh) bướu cổ", "None"],
  ["body", "cơ thể", "/ˈbɑːdi/"],
  ["thin", "gầy, ốm", "/θɪn/"],
  ["dietary", "(thuộc) chế độ ăn uống", "/ˈdaɪəteri/"],
  ["fat", "béo, nặng cân", "/fæt/"],
  ["overweight", "béo, thừa cân", "/ˌəʊvərˈweɪt/"],
  ["eating disorder", "(chứng) rối loạn ăn uống", "/ˈiːtɪŋ dɪsɔːrdər/"],
  ["nutrient", "chất dinh dưỡng", "/ˈnuːtriənt/"],
  ["ingredient", "thành phần, nguyên liệu", "/ɪnˈɡriːdiənt/"],
  ["allergy", "(bệnh) dị ứng", "/ˈælərdʒi/"],
  ["vitamin", "vi-ta-min", "/ˈvaɪtəmɪn/"],
  ["overeat", "ăn quá nhiều, ăn quá mức", "/ˌəʊvərˈiːt/"],
  ["nutritious", "bổ dưỡng", "/nuˈtrɪʃəs/"],
  ["vegetarian", "người ăn chay", "/ˌvedʒəˈteriən/"],
  ["mineral", "khoáng chất, khoáng sản", "/ˈmɪnərəl/"],
  ["earthquake", "(trận) động đất", "/ˈɜːrθkweɪk/"],
  ["aftershock", "(cơn) dư chấn", "/ˈæftərʃɑːk/"],
  ["flood", "làm ngập lụt, nhấn chìm", "/flʌd/"],
  ["drought", "hạn hán", "/draʊt/"],
  ["famine", "nạn đói", "/ˈfæmɪn/"],
  ["avalanche", "(trận) tuyết lở", "/ˈævəlæntʃ/"],
  ["blizzard", "bão tuyết", "/ˈblɪzərd/"],
  ["tornado", "lốc xoáy", "/tɔːrˈneɪdəʊ/"],
  ["forest fire", "(vụ) cháy rừng", "None"],
  ["hurricane", "(cơn) bão", "/ˈhɜːrəkeɪn/"],
  ["evacuation", "(sự) di tản, sơ tán", "/ɪˌvækjuˈeɪʃn/"],
  ["evacuate", "di tản, sơ tán", "/ɪˈvækjueɪt/"],
  ["catastrophic", "thảm khốc, thê thảm", "/ˌkætəˈstrɑːfɪk/"],
  ["nationwide", "toàn quốc, khắp cả nước", "/ˌneɪʃnˈwaɪd/"],
  ["precaution", "sự phòng ngừa, sự đề phòng", "/prɪˈkɔːʃn/"],
  ["avenue", "đại lộ", "/ˈævənuː/"],
  ["between", "ở giữa", "/bɪˈtwiːn/"],
  ["beside", "bên, bên cạnh", "/bɪˈsaɪd/"],
  ["behind", "(vị trí) ở phía sau, ở đằng sau", "/bɪˈhaɪnd/"],
  ["bench", "ghế dài", "/bentʃ/"],
  ["curve", "cua, uốn cong, bẻ cong", "/kɜːrv/"],
  ["go past", "đi qua, vượt qua", "None"],
  ["go down", "đi xuống đâu, đi tới đâu", "None"],
  ["in front of", "(vị trí) ở phía trước, ở đằng trước", "None"],
  ["opposite", "trước mặt, đối diện", "/ˈɑːpəzɪt/"],
  ["near", "gần", "/nɪr/"],
  ["turn right", "rẽ phải", "None"],
  ["turn left", "rẽ trái", "None"],
  ["junction", "giao lộ", "/ˈdʒʌŋkʃn/"],
  ["turning", "ngã rẽ", "/ˈtɜːrnɪŋ/"],
  ["roundabout", "bùng binh", "/ˈraʊndəbaʊt/"],
  ["pavement", "vỉa hè", "/ˈpeɪvmənt/"],
  ["bar", "quán rượu", "/bɑːr/"],
  ["chef", "đầu bếp, bếp trưởng", "/ʃef/"],
  ["waiter", "bồi bàn, nam phục vụ", "/ˈweɪtər/"],
  ["waitress", "nữ phục vụ, cô hầu bàn", "/ˈweɪtrəs/"],
  ["bill", "hóa đơn", "/bɪl/"],
  ["service", "dịch vụ, sự phục vụ", "/ˈsɜːrvɪs/"],
  ["tip", "tiền boa", "/tɪp/"],
  ["knife", "con dao", "/naɪf/"],
  ["bowl", "(đo lường) bát, chén", "/bəʊl/"],
  ["teapot", "bình trà, ấm pha trà", "/ˈtiːpɑːt/"],
  ["glass", "(đo lường) ly, cốc", "/ɡlæs/"],
  ["breakfast", "bữa ăn sáng", "/ˈbrekfəst/"],
  ["dinner", "bữa ăn tối", "/ˈdɪnər/"],
  ["lunch", "bữa ăn trưa", "/lʌntʃ/"],
  ["booking office", "phòng bán vé", "/ˈbʊkɪŋ ɑːfɪs/"],
  ["menu", "thực đơn", "/ˈmenjuː/"],
  ["starter", "món khai vị", "/ˈstɑːrtər/"],
  ["main course", "món chính", "/ˌmeɪn ˈkɔːrs/"],
  ["dessert", "món tráng miệng", "/dɪˈzɜːrt/"],
  ["advanced", "tiên tiến", "/ədˈvænst/"],
  ["equip", "trang bị", "/ɪˈkwɪp/"],
  ["express mail", "chuyển phát nhanh", "None"],
  ["facsimile", "hệ thống chuyển fax, dịch vụ chuyển fax", "/fækˈsɪməli/"],
  ["graphic", "hình ảnh, hình đồ họa", "/ˈɡræfɪk/"],
  ["Messenger Call Service", "Dịch vụ Điện thoại", "None"],
  ["notify", "thông báo", "/ˈnəʊtɪfaɪ/"],
  ["parcel", "bưu kiện, bưu phẩm", "/ˈpɑːrsl/"],
  ["press", "báo chí", "/pres/"],
  ["receive", "nhận", "/rɪˈsiːv/"],
  ["recipient", "người nhận", "/rɪˈsɪpiənt/"],
  ["secure", "(cảm giác) yên tâm, an toàn", "/sɪˈkjʊr/"],
  ["service", "(ngành) dịch vụ", "/ˈsɜːrvɪs/"],
  ["spacious", "rộng rãi", "/ˈspeɪʃəs/"],
  ["speedy", "nhanh chóng", "/ˈspiːdi/"],
  ["staff", "nhân viên", "/stæf/"],
  ["subscribe", "đặt mua báo", "/səbˈskraɪb/"],
  ["surface mail", "thư gửi bằng đường bộ", "/ˈsɜːrfɪs meɪl/"],
  ["technology", "công nghệ", "/tekˈnɑːlədʒi/"],
  ["thoughtful", "ân cần, chu đáo", "/ˈθɔːtfl/"],
  ["transfer", "dời, chuyển; di chuyển", "/trænsˈfɜːr/"],
  ["transmit", "truyền thanh, phát sóng", "/trænzˈmɪt/"],
  ["well-trained", "(được) đào tạo bài bản, thuần thục", "None"],
  ["clerk", "viên thư ký, nhân viên trực", "/klɜːrk/"],
  ["keep-fit", "(bài tập) thể dục", "/ˌkiːp ˈfɪt/"],
  ["regular", "(xảy ra) thường xuyên", "/ˈreɡjələr/"],
  ["diabetes", "(bệnh) tiểu đường", "/ˌdaɪəˈbiːtiːz/"],
  ["dietitian", "chuyên gia dinh dưỡng", "None"],
  ["goiter", "(bệnh) bướu cổ", "None"],
  ["body", "cơ thể", "/ˈbɑːdi/"],
  ["thin", "gầy, ốm", "/θɪn/"],
  ["dietary", "(thuộc) chế độ ăn uống", "/ˈdaɪəteri/"],
  ["fat", "béo, nặng cân", "/fæt/"],
  ["overweight", "béo, thừa cân", "/ˌəʊvərˈweɪt/"],
  ["eating disorder", "(chứng) rối loạn ăn uống", "/ˈiːtɪŋ dɪsɔːrdər/"],
  ["nutrient", "chất dinh dưỡng", "/ˈnuːtriənt/"],
  ["ingredient", "thành phần, nguyên liệu", "/ɪnˈɡriːdiənt/"],
  ["allergy", "(bệnh) dị ứng", "/ˈælərdʒi/"],
  ["vitamin", "vi-ta-min", "/ˈvaɪtəmɪn/"],
  ["overeat", "ăn quá nhiều, ăn quá mức", "/ˌəʊvərˈiːt/"],
  ["nutritious", "bổ dưỡng", "/nuˈtrɪʃəs/"],
  ["vegetarian", "người ăn chay", "/ˌvedʒəˈteriən/"],
  ["mineral", "khoáng chất, khoáng sản", "/ˈmɪnərəl/"],
  ["keep-fit", "(bài tập) thể dục", "/ˌkiːp ˈfɪt/"],
  ["regular", "(xảy ra) thường xuyên", "/ˈreɡjələr/"],
  ["diabetes", "(bệnh) tiểu đường", "/ˌdaɪəˈbiːtiːz/"],
  ["dietitian", "chuyên gia dinh dưỡng", "None"],
  ["goiter", "(bệnh) bướu cổ", "None"],
  ["body", "cơ thể", "/ˈbɑːdi/"],
  ["thin", "gầy, ốm", "/θɪn/"],
  ["dietary", "(thuộc) chế độ ăn uống", "/ˈdaɪəteri/"],
  ["fat", "béo, nặng cân", "/fæt/"],
  ["overweight", "béo, thừa cân", "/ˌəʊvərˈweɪt/"],
  ["eating disorder", "(chứng) rối loạn ăn uống", "/ˈiːtɪŋ dɪsɔːrdər/"],
  ["nutrient", "chất dinh dưỡng", "/ˈnuːtriənt/"],
  ["ingredient", "thành phần, nguyên liệu", "/ɪnˈɡriːdiənt/"],
  ["allergy", "(bệnh) dị ứng", "/ˈælərdʒi/"],
  ["vitamin", "vi-ta-min", "/ˈvaɪtəmɪn/"],
  ["overeat", "ăn quá nhiều, ăn quá mức", "/ˌəʊvərˈiːt/"],
  ["nutritious", "bổ dưỡng", "/nuˈtrɪʃəs/"],
  ["vegetarian", "người ăn chay", "/ˌvedʒəˈteriən/"],
  ["mineral", "khoáng chất, khoáng sản", "/ˈmɪnərəl/"],
  ["price", "giá, giá cả", "/praɪs/"],
  ["pile-up", "(tai nạn) vụ va chạm", "None"],
  ["orchid", "(cây) lan, phong lan", "/ˈɔːrkɪd/"],
  ["magnificence", "sự hùng vĩ, tráng lệ", "/mæɡˈnɪfɪsns/"],
  ["luggage", "hành lí", "/ˈlʌɡɪdʒ/"],
  ["lush", "tươi tốt, sum sê", "/lʌʃ/"],
  ["inaccessible", "khó đến, khó đạt", "/ˌɪnækˈsesəbl/"],
  ["imperial", "(thuộc) hoàng đế, cung đình", "/ɪmˈpɪriəl/"],
  ["hyphen", "dấu gạch nối (trong từ nối)", "/ˈhaɪfn/"],
  ["explore", "khám phá, thăm dò, thám hiểm (địa điểm)", "/ɪkˈsplɔːr/"],
  ["exotic", "ngoại lai, kỳ lạ", "/ɪɡˈzɑːtɪk/"],
  ["confusion", "(sự) nhầm lẫn, sai sót", "/kənˈfjuːʒn/"],
  ["checkout", "quầy thanh toán", "/ˈtʃekaʊt/"],
  ["check-in", "(sân bay) quầy thủ tục đăng ký", "None"],
  ["breathtaking", "ngoạn mục, ấn tượng", "/ˈbreθteɪkɪŋ/"],
  ["accommodation", "chỗ ở", "/əˌkɑːməˈdeɪʃn/"],
  ["air", "khí, không khí", "/er/"],
  ["affordable", "(giá cả) phải chăng, rẻ", "/əˈfɔːrdəbl/"],
  ["price", "giá, giá cả", "/praɪs/"],
  ["pile-up", "(tai nạn) vụ va chạm", "None"],
  ["orchid", "(cây) lan, phong lan", "/ˈɔːrkɪd/"],
  ["magnificence", "sự hùng vĩ, tráng lệ", "/mæɡˈnɪfɪsns/"],
  ["luggage", "hành lí", "/ˈlʌɡɪdʒ/"],
  ["lush", "tươi tốt, sum sê", "/lʌʃ/"],
  ["inaccessible", "khó đến, khó đạt", "/ˌɪnækˈsesəbl/"],
  ["imperial", "(thuộc) hoàng đế, cung đình", "/ɪmˈpɪriəl/"],
  ["hyphen", "dấu gạch nối (trong từ nối)", "/ˈhaɪfn/"],
  ["explore", "khám phá, thăm dò, thám hiểm (địa điểm)", "/ɪkˈsplɔːr/"],
  ["exotic", "ngoại lai, kỳ lạ", "/ɪɡˈzɑːtɪk/"],
  ["confusion", "(sự) nhầm lẫn, sai sót", "/kənˈfjuːʒn/"],
  ["checkout", "quầy thanh toán", "/ˈtʃekaʊt/"],
  ["check-in", "(sân bay) quầy thủ tục đăng ký", "None"],
  ["breathtaking", "ngoạn mục, ấn tượng", "/ˈbreθteɪkɪŋ/"],
  ["accommodation", "chỗ ở", "/əˌkɑːməˈdeɪʃn/"],
  ["air", "khí, không khí", "/er/"],
  ["affordable", "(giá cả) phải chăng, rẻ", "/əˈfɔːrdəbl/"],
  ["battery", "pin", "/ˈbætəri/"],
  ["channel", "kênh (truyền hình)", "/ˈtʃænl/"],
  ["chat room", "phòng trò chuyện trực tuyến", "/ˈtʃæt ruːm/"],
  ["colleague", "đồng nghiệp, cộng sự", "/ˈkɑːliːɡ/"],
  ["audience", "khán giả, người xem", "/ˈɔːdiəns/"],
  ["communicate", "giao tiếp, truyền đạt", "/kəˈmjuːnɪkeɪt/"],
  ["corridor", "hành lang", "/ˈkɔːrɪdɔːr/"],
  ["decade", "thập kỷ", "/ˈdekeɪd/"],
  ["delay", "hoãn, chặn lại", "/dɪˈleɪ/"],
  ["disappear", "biến mất, tan biến", "/ˌdɪsəˈpɪr/"],
  ["explain", "giải thích, diễn tả", "/ɪkˈspleɪn/"],
  ["express", "bày tỏ, thể hiện", "/ɪkˈspres/"],
  ["function", "chức năng", "/ˈfʌŋkʃn/"],
  ["graphic", "hình ảnh, hình đồ họa", "/ˈɡræfɪk/"],
  ["immediately", "ngay lập tức", "/ɪˈmiːdiətli/"],
  ["instantly", "ngay tức khắc; lập tức", "/ˈɪnstəntli/"],
  ["interact", "Tương tác", "/ˌɪntərˈækt/"],
  ["keep in touch", "giữ liên lạc", "None"],
  ["battery", "pin", "/ˈbætəri/"],
  ["channel", "kênh (truyền hình)", "/ˈtʃænl/"],
  ["chat room", "phòng trò chuyện trực tuyến", "/ˈtʃæt ruːm/"],
  ["colleague", "đồng nghiệp, cộng sự", "/ˈkɑːliːɡ/"],
  ["audience", "khán giả, người xem", "/ˈɔːdiəns/"],
  ["communicate", "giao tiếp, truyền đạt", "/kəˈmjuːnɪkeɪt/"],
  ["corridor", "hành lang", "/ˈkɔːrɪdɔːr/"],
  ["decade", "thập kỷ", "/ˈdekeɪd/"],
  ["delay", "hoãn, chặn lại", "/dɪˈleɪ/"],
  ["disappear", "biến mất, tan biến", "/ˌdɪsəˈpɪr/"],
  ["explain", "giải thích, diễn tả", "/ɪkˈspleɪn/"],
  ["express", "bày tỏ, thể hiện", "/ɪkˈspres/"],
  ["function", "chức năng", "/ˈfʌŋkʃn/"],
  ["graphic", "hình ảnh, hình đồ họa", "/ˈɡræfɪk/"],
  ["immediately", "ngay lập tức", "/ɪˈmiːdiətli/"],
  ["instantly", "ngay tức khắc; lập tức", "/ˈɪnstəntli/"],
  ["interact", "Tương tác", "/ˌɪntərˈækt/"],
  ["keep in touch", "giữ liên lạc", "None"],
  ["administrative", "(thuộc) hành chính", "/ədˈmɪnɪstreɪtɪv/"],
  ["astounding", "đáng kinh ngạc, khó tin", "/əˈstaʊndɪŋ/"],
  ["cavern", "hang động, động", "/ˈkævərn/"],
  ["citadel", "thành lũy", "/ˈsɪtədəl/"],
  ["complex", "phức tạp", "/kəmˈpleks/"],
  ["contestant", "thí sinh", "/kənˈtestənt/"],
  ["fortress", "pháo đài", "/ˈfɔːrtrəs/"],
  ["geological", "(thuộc) địa chất", "/ˌdʒiːəˈlɑːdʒɪkl/"],
  ["limestone", "đá vôi", "/ˈlaɪmstəʊn/"],
  ["paradise", "thiên đường", "/ˈpærədaɪs/"],
  ["picturesque", "đẹp như tranh vẽ", "/ˌpɪktʃəˈresk/"],
  ["recognition", "sự nhận diện, sự nhận dạng", "/ˌrekəɡˈnɪʃn/"],
  ["rickshaw", "xe kéo", "/ˈrɪkʃɔː/"],
  ["round", "(hình) tròn, cầu", "/raʊnd/"],
  ["sculpture", "tác phẩm điêu khắc", "/ˈskʌlptʃər/"],
  ["administrative", "(thuộc) hành chính", "/ədˈmɪnɪstreɪtɪv/"],
  ["astounding", "đáng kinh ngạc, khó tin", "/əˈstaʊndɪŋ/"],
  ["cavern", "hang động, động", "/ˈkævərn/"],
  ["citadel", "thành lũy", "/ˈsɪtədəl/"],
  ["complex", "phức tạp", "/kəmˈpleks/"],
  ["contestant", "thí sinh", "/kənˈtestənt/"],
  ["fortress", "pháo đài", "/ˈfɔːrtrəs/"],
  ["geological", "(thuộc) địa chất", "/ˌdʒiːəˈlɑːdʒɪkl/"],
  ["limestone", "đá vôi", "/ˈlaɪmstəʊn/"],
  ["paradise", "thiên đường", "/ˈpærədaɪs/"],
  ["picturesque", "đẹp như tranh vẽ", "/ˌpɪktʃəˈresk/"],
  ["recognition", "sự nhận diện, sự nhận dạng", "/ˌrekəɡˈnɪʃn/"],
  ["rickshaw", "xe kéo", "/ˈrɪkʃɔː/"],
  ["round", "(hình) tròn, cầu", "/raʊnd/"],
  ["sculpture", "tác phẩm điêu khắc", "/ˈskʌlptʃər/"],
];

function show_word() {
  let index = Math.floor(Math.random() * list_word.length);
  if (repeat) {
    if (appeared.length == list_word.length) {
      appeared = [];
    }
    while (appeared.includes(index)) {
      index = Math.floor(Math.random() * list_word.length);
    }
    appeared.push(index);
  }
  word_en.innerText = list_word[index][0];
  word_vi.innerText = list_word[index][1];
  word_pro.innerText = list_word[index][2];
}
show_word();
